# Generated by Django 6.0.3 on 2026-03-19 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Stok Adı')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barkod')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('lt', 'Litre'), ('ml', 'Mililitre'), ('adet', 'Adet'), ('porsiyon', 'Porsiyon'), ('paket', 'Paket'), ('kutu', 'Kutu')], default='adet', max_length=20, verbose_name='Birim')),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Mevcut Miktar')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Minimum Miktar')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Maliyet')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Stok Kalemi',
                'verbose_name_plural': 'Stok Kalemleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış'), ('ADJUSTMENT', 'Düzeltme'), ('WASTE', 'Fire/Zayi'), ('TRANSFER', 'Transfer')], max_length=20, verbose_name='Hareket Tipi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miktar')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referans')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tedarikçi Adı')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Kişisi')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('stock_items', models.ManyToManyField(blank=True, related_name='suppliers', to='inventory.stockitem', verbose_name='Tedarik Edilen Ürünler')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['sku'], name='inventory_s_sku_386565_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['branch', 'is_active'], name='inventory_s_branch__7d302c_idx'),
        ),
    ]
