# Generated by Django 6.0.3 on 2026-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('lt', 'Litre'), ('ml', 'Mililitre'), ('adet', 'Adet'), ('porsiyon', 'Porsiyon'), ('paket', 'Paket'), ('kutu', 'Kutu')], max_length=20, null=True, verbose_name='Birim'),
        ),
    ]
