# Generated by Django 6.0.2 on 2026-03-19 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kategori Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.stockcategory', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Stok Kategorisi',
                'verbose_name_plural': 'Stok Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.stockcategory', verbose_name='Kategori'),
        ),
    ]
