# Generated by Django 6.0.2 on 2026-03-19 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockcategory_stockitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Birim Adı')),
                ('short_name', models.CharField(max_length=20, verbose_name='Kısa Ad')),
                ('multiplier', models.DecimalField(decimal_places=3, default=1.0, max_digits=12, verbose_name='Çarpan')),
            ],
            options={
                'verbose_name': 'Miktar Birimi',
                'verbose_name_plural': 'Miktar Birimleri',
                'ordering': ['name'],
            },
        ),
    ]
