# Generated by Django 6.0.3 on 2026-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(default='adet', help_text='StockUnit.short_name ile eşleşmeli (Birim Tanımlamalarından)', max_length=20, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(blank=True, help_text='StockUnit.short_name ile eşleşmeli', max_length=20, null=True, verbose_name='Birim'),
        ),
    ]
