# Generated by Django 6.0.3 on 2026-03-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockitem_unit_alter_stockmovement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.stockcategory', verbose_name='Kategori'),
        ),
    ]
