# Generated by Django 6.0.3 on 2026-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Son Giriş Fiyatı'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat'),
        ),
    ]
