# Generated by Django 6.0.3 on 2026-04-03 20:09

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def migrate_stock_quantity_to_warehouse(apps, schema_editor):
    StockItem = apps.get_model('inventory', 'StockItem')
    WarehouseStockLevel = apps.get_model('warehouse', 'warehousestocklevel')
    Warehouse = apps.get_model('warehouse', 'Warehouse')
    
    default_warehouse = Warehouse.objects.filter(is_default=True).first()
    if not default_warehouse:
        default_warehouse = Warehouse.objects.first()
    
    if not default_warehouse:
        return
    
    for item in StockItem.objects.all():
        if item.current_quantity and item.current_quantity > 0:
            level, created = WarehouseStockLevel.objects.get_or_create(
                warehouse=default_warehouse,
                stock_item=item,
                defaults={
                    'quantity': item.current_quantity,
                    'minimum_quantity': item.minimum_quantity or Decimal('0'),
                }
            )
            if not created:
                level.quantity = item.current_quantity
                level.save(update_fields=['quantity'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockitem_cost_per_unit_and_more'),
        ('warehouse', '0006_remove_warehouse_branch'),
    ]

    operations = [
        migrations.RunPython(migrate_stock_quantity_to_warehouse, reverse_migration),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='inventory_s_branch__7d302c_idx',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='warehouse.warehouse', verbose_name='Depo'),
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='current_quantity',
        ),
    ]
