# Generated by Django 6.0.3 on 2026-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_based_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
