# Generated by Django 6.0.3 on 2026-04-08 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockcategory_is_active'),
        ('warehouse', '0007_purchaseorder_deficiency_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Mal kabulleri üzerinden otomatik hesaplanır.', max_digits=10, verbose_name='Ağırlıklı Ortalama Maliyet'),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Parti/Lot Numarası')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi (SKT)')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Kalan Miktar')),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Başlangıç Miktarı')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Kabul Tarihi')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='warehouse.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Partisi',
                'verbose_name_plural': 'Stok Partileri',
                'ordering': ['expiry_date', 'received_at'],
                'indexes': [models.Index(fields=['warehouse', 'stock_item', 'expiry_date'], name='inventory_s_warehou_29c02a_idx'), models.Index(fields=['expiry_date'], name='inventory_s_expiry__cf6e69_idx')],
            },
        ),
    ]
