# Generated by Django 6.0.3 on 2026-04-09 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_average_cost_and_stock_lot'),
        ('orders', '0007_order_order_type'),
        ('warehouse', '0007_purchaseorder_deficiency_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('RESERVED', 'Rezerve'), ('COMMITTED', 'Commit'), ('RELEASED', 'Serbest')], default='RESERVED', max_length=20, verbose_name='Durum')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.orderitem', verbose_name='Sipariş Kalemi')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='warehouse.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Rezervasyonu',
                'verbose_name_plural': 'Stok Rezervasyonları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'stock_item', 'status'], name='inventory_s_warehou_617a45_idx'), models.Index(fields=['order_item', 'status'], name='inventory_s_order_i_57ff40_idx')],
            },
        ),
    ]
