# Generated by Django 6.0.3 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stock_receipt_draft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockreceiptdraft',
            new_name='inventory_s_user_id_7737c8_idx',
            old_name='inventory_s_user_id_8f0b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreceiptdraft',
            new_name='inventory_s_warehou_8766d6_idx',
            old_name='inventory_s_warehou_3a9c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreceiptdraftline',
            new_name='inventory_s_draft_i_3584c5_idx',
            old_name='inventory_s_draft_i_7e4a2b_idx',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=6, default=0, help_text='-1 = sınırsız (kritik stok kontrollerinde dikkate alınmaz).', max_digits=12, verbose_name='Minimum Miktar'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Başlangıç Miktarı'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Kalan Miktar'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='stockreceiptdraftline',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='multiplier',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='Çarpan'),
        ),
    ]
