# Generated by Django 6.0.3 on 2026-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_increase_decimal_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockunit',
            name='category',
            field=models.CharField(choices=[('WEIGHT', 'Ağırlık (kg, g, ...)'), ('VOLUME', 'Hacim (Lt, ml, ...)'), ('COUNT', 'Adet / Sayı (adet, pk, kutu, ...)'), ('OTHER', 'Diğer')], default='OTHER', help_text='Birim dönüşümü yalnızca aynı kategorideki birimler arasında yapılır.', max_length=10, verbose_name='Birim Kategorisi'),
        ),
    ]
