# Generated by Django 6.0.4 on 2026-05-07 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_unit_category'),
        ('warehouse', '0008_increase_decimal_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='inventory_s_stock_i_73796c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', '-created_at'], name='inventory_s_warehou_2b0ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
    ]
