# Generated by Django 6.0.3 on 2026-05-11 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockmovement_inventory_s_stock_i_73796c_idx_and_more'),
        ('warehouse', '0008_increase_decimal_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'movement_type', '-created_at'], name='inventory_s_warehou_6fdd83_idx'),
        ),
    ]
