# Generated by Django 6.0.5 on 2026-05-22 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0019_alter_branch_options_alter_table_options_and_more'),
        ('inventory', '0017_stockmovement_inventory_s_warehou_6fdd83_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('PRIORITY_CONSUME', 'Öncelikli Tüketim'), ('TRANSFER_SUGGEST', 'Transfer Önerisi'), ('PLAN_NOTE', 'Plan Revizyon Notu')], max_length=32, verbose_name='Aksiyon Tipi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Not')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_actions', to='branches.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_actions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_actions', to='inventory.stocklot', verbose_name='Stok Partisi')),
            ],
            options={
                'verbose_name': 'SKT Aksiyonu',
                'verbose_name_plural': 'SKT Aksiyonları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock_lot', '-created_at'], name='inventory_e_stock_l_0c1d08_idx'), models.Index(fields=['-created_at'], name='inventory_e_created_97dbfb_idx')],
            },
        ),
    ]
