# Generated by Django 6.0.5 on 2026-05-28 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_expiryaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Sistem Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Madde Adı')),
                ('prevalence_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Küresel Sıklık Oranı (%)')),
                ('risk_score', models.PositiveSmallIntegerField(default=1, help_text='1 (düşük) – 10 (yüksek)', verbose_name='Risk Puanı')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Alerjen Maddesi',
                'verbose_name_plural': 'Alerjen Maddeleri',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='stock_items', to='inventory.allergen', verbose_name='Alerjen Maddeler'),
        ),
    ]
