# Generated by Django 6.0.6 on 2026-06-11 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_allergen_stockitem_allergens'),
        ('prep', '0008_preptemplate_assigned_to'),
        ('production_planning', '0002_prodplan_softdelete_unique'),
        ('warehouse', '0009_remove_deficiencyreport_warehouse_d_status_c23cb7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('CONSUMED', 'Tüketildi'), ('RELEASED', 'Serbest Bırakıldı')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('plan_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='production_planning.productionplanline', verbose_name='Üretim Planı Satırı')),
                ('prep_task', models.ForeignKey(blank=True, help_text='Hangi hazırlık görevi için rezerve edildiğini takip eder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='prep.preptask', verbose_name='Hazırlık Görevi')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reservations', to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reservations', to='warehouse.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Üretim Stok Rezervasyonu',
                'verbose_name_plural': 'Üretim Stok Rezervasyonları',
                'indexes': [models.Index(fields=['warehouse', 'stock_item', 'status'], name='inventory_p_warehou_7cb8f0_idx'), models.Index(fields=['plan_line', 'status'], name='inventory_p_plan_li_25b79f_idx'), models.Index(fields=['prep_task', 'status'], name='inventory_p_prep_ta_342679_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('stock_item', 'warehouse', 'plan_line'), name='prodreservation_unique_item_warehouse_planline_active')],
            },
        ),
    ]
