# Generated by Django 6.0.6 on 2026-06-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_productionreservation'),
        ('production_planning', '0002_prodplan_softdelete_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreservation',
            name='plan_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='production_planning.productionplanline', verbose_name='Üretim Planı Satırı'),
        ),
    ]
