# Generated by Django 6.0.6 on 2026-06-12 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_productionreservation_nullable_planline'),
        ('orders', '0021_orderitem_waiter_acknowledged_at'),
        ('sales', '0011_alter_sale_original_payment_method_and_more'),
        ('warehouse', '0009_remove_deficiencyreport_warehouse_d_status_c23cb7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Kapaklı/kutulu ürünlerde fiziksel iade mümkün. True ise iptal/iade akışında fiziksel kontrol talep edilir.', verbose_name='İade Edilebilir'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış'), ('ADJUSTMENT', 'Düzeltme'), ('WASTE', 'Fire/Zayi'), ('TRANSFER', 'Transfer'), ('RETURN', 'İade'), ('DISPOSAL', 'İmha')], max_length=20, verbose_name='Hareket Tipi'),
        ),
        migrations.CreateModel(
            name='ReturnDisposalFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flow_type', models.CharField(choices=[('RETURN_TO_SUPPLIER', 'Tedarikçiye İade'), ('CUSTOMER_RETURN', 'Müşteri İadesi'), ('DISPOSAL', 'İmha'), ('END_OF_DAY_SURPLUS', 'Gün Sonu Fazlası')], max_length=30, verbose_name='Akış Tipi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING_APPROVAL', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('reason_code', models.CharField(blank=True, max_length=50, verbose_name='Neden Kodu')),
                ('reason_text', models.TextField(blank=True, verbose_name='Neden Açıklaması')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_return_flows', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_return_flows', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Sipariş')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='Satış')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_flows_from', to='warehouse.warehouse', verbose_name='Kaynak Depo')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Tedarikçi')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_flows_to', to='warehouse.warehouse', verbose_name='Hedef Depo')),
            ],
            options={
                'verbose_name': 'İade/İmha Akışı',
                'verbose_name_plural': 'İade/İmha Akışları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnDisposalFlowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('is_packaging_intact', models.BooleanField(blank=True, help_text='Kapaklı/kutulu ürünlerde fiziksel kontrol sonucu', null=True, verbose_name='Ambalaj Sağlam mı?')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Kontrol Tarihi')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.returndisposalflow', verbose_name='Akış')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot', verbose_name='Lot/Parti')),
            ],
            options={
                'verbose_name': 'İade/İmha Kalemi',
                'verbose_name_plural': 'İade/İmha Kalemleri',
            },
        ),
        migrations.AddIndex(
            model_name='returndisposalflow',
            index=models.Index(fields=['status', 'flow_type'], name='inventory_r_status_a70f04_idx'),
        ),
        migrations.AddIndex(
            model_name='returndisposalflow',
            index=models.Index(fields=['sale'], name='inventory_r_sale_id_e325bc_idx'),
        ),
        migrations.AddIndex(
            model_name='returndisposalflow',
            index=models.Index(fields=['order'], name='inventory_r_order_i_72ee5f_idx'),
        ),
    ]
