# Generated by Django 6.0.6 on 2026-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockitem_is_returnable_and_more'),
        ('orders', '0022_orderitem_return_flow_orderitem_waste_recorded'),
        ('warehouse', '0009_remove_deficiencyreport_warehouse_d_status_c23cb7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['warehouse', 'stock_item', 'quantity', 'is_active'], name='inv_sl_wh_si_qty_act_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['is_active', 'warehouse', 'stock_item', 'status'], name='inv_sr_act_wh_si_st_idx'),
        ),
    ]
