# Generated by Django 6.0.6 on 2026-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stocklot_inv_sl_wh_si_qty_act_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocklot',
            name='inv_sl_wh_si_qty_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockreservation',
            name='inv_sr_act_wh_si_st_idx',
        ),
    ]
