# Generated by Django 6.0.6 on 2026-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_stocklot_inv_sl_wh_si_qty_act_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış'), ('ADJUSTMENT', 'Düzeltme'), ('WASTE', 'Fire/Zayi'), ('TRANSFER', 'Transfer'), ('RETURN', 'İade'), ('CANCEL', 'İptal'), ('DISPOSAL', 'İmha')], max_length=20, verbose_name='Hareket Tipi'),
        ),
    ]
