# Generated by Django 6.0.6 on 2026-06-27 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_stockmovement_cancel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Parti Numarası (snapshot)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='SKT (snapshot)')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_consumptions', to='inventory.stockmovement', verbose_name='Stok Hareketi')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_consumptions', to='inventory.stocklot', verbose_name='Stok Partisi')),
            ],
            options={
                'verbose_name': 'Stok Hareketi Lot Satırı',
                'verbose_name_plural': 'Stok Hareketi Lot Satırları',
                'indexes': [models.Index(fields=['movement'], name='inventory_s_movemen_85a4a4_idx'), models.Index(fields=['stock_lot'], name='inventory_s_stock_l_172c40_idx')],
            },
        ),
    ]
