# Generated by Django 6.0.6 on 2026-07-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_orderitemingredientcost'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderitemingredientcost',
            new_name='inventory_o_order_i_589921_idx',
            old_name='invent_ordi_order_i_cd4e4e_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitemingredientcost',
            new_name='inventory_o_branch__d025a6_idx',
            old_name='invent_ordi_branch__b27a84_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitemingredientcost',
            new_name='inventory_o_stock_i_5c7c77_idx',
            old_name='invent_ordi_stock_i_9e7b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitemingredientcost',
            new_name='inventory_o_movemen_20189d_idx',
            old_name='invent_ordi_movement_6ca69c_idx',
        ),
    ]
