# Generated by Django 6.0.3 on 2026-04-19 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, verbose_name='Şablon Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Kod')),
                ('category', models.CharField(choices=[('SALES', 'Satış Raporları'), ('STOCK', 'Stok/Envanter Raporları'), ('POS', 'Adisyon/Fiş Şablonları'), ('INVOICE', 'Fatura Şablonları'), ('CUSTOM', 'Özel Raporlar')], default='CUSTOM', max_length=20, verbose_name='Kategori')),
                ('html_body', models.TextField(help_text='Template formatında HTML içeriği.', verbose_name='HTML Gövdesi')),
                ('css_styles', models.TextField(blank=True, default='', help_text='Rapor için özel CSS kuralları.', verbose_name='CSS Stilleri')),
                ('is_default', models.BooleanField(default=False, help_text='Aynı kategorideki bir işlem için bu şablonun varsayılan olarak kullanılıp kullanılmayacağını belirler.', verbose_name='Varsayılan mı?')),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
                'ordering': ['category', 'name'],
            },
        ),
    ]
