# Generated by Django 6.0.4 on 2026-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='category',
            field=models.CharField(choices=[('POS_RECEIPT', 'POS Fişi / Adisyon'), ('KITCHEN_TICKET', 'Mutfak Fişi'), ('WAITER_TICKET', 'Garson Fişi'), ('MODULE_REPORT', 'Modül Raporu (Sabit)'), ('INVOICE', 'Fatura Şablonu'), ('CUSTOM', 'Özel Şablon')], default='CUSTOM', max_length=20, verbose_name='Kategori'),
        ),
    ]
