# Generated by Django 6.0.4 on 2026-05-03 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reporttemplate_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, verbose_name='Şablon Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Kod')),
                ('category', models.CharField(choices=[('POS_RECEIPT', 'POS Fişi / Adisyon'), ('KITCHEN_TICKET', 'Mutfak Fişi'), ('WAITER_TICKET', 'Garson Fişi')], default='POS_RECEIPT', max_length=20, verbose_name='Kategori')),
                ('paper_width', models.PositiveSmallIntegerField(default=48, help_text='Satır başına karakter sayısı. 58mm→32, 80mm→48.', verbose_name='Kağıt Genişliği (karakter)')),
                ('layout_json', models.JSONField(default=list, help_text='ESC/POS komutlarına dönüştürülecek blok listesi.', verbose_name='Şablon Blokları')),
                ('is_default', models.BooleanField(default=False, help_text='Aynı kategorideki işlem için varsayılan şablon.', verbose_name='Varsayılan mı?')),
            ],
            options={
                'verbose_name': 'Fiş Şablonu',
                'verbose_name_plural': 'Fiş Şablonları',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('category',), name='unique_default_receipt_per_category')],
            },
        ),
    ]
