# Generated by Django migration — slug tekilliği yalnızca is_active=True satırlar için (soft delete sonrası yeniden kullanım)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_add_receipt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Kod'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('slug',),
                name='uniq_reporttemplate_slug_among_active',
            ),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Kod'),
        ),
        migrations.AddConstraint(
            model_name='receipttemplate',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('slug',),
                name='uniq_receipttemplate_slug_among_active',
            ),
        ),
    ]
