# Generated by Django 6.0.6 on 2026-07-02 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0021_branch_new_fields'),
        ('reservations', '0003_reservationbranchsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'scheduled_date'], name='reservation_branch__45cbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'status', 'scheduled_date'], name='reservation_branch__4493d4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='reservation_schedul_e09a67_idx'),
        ),
    ]
