# Generated by Django 6.0.6 on 2026-07-04 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0021_branch_new_fields'),
        ('customers', '0001_initial'),
        ('orders', '0024_add_performance_indexes'),
        ('pos_display', '0009_posterminal_fiscal_settings_posterminal_fiscal_type'),
        ('sales', '0017_fiscal_pending_basket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=180, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_customer_display_active', models.BooleanField(default=True, verbose_name='Müşteri ekranında aktif')),
                ('is_smart_table_active', models.BooleanField(default=False, verbose_name='Smart Table üzerinde aktif')),
                ('branches', models.ManyToManyField(related_name='guest_feedback_surveys', to='branches.branch', verbose_name='Şubeler')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=500, verbose_name='Soru')),
                ('answer_type', models.CharField(choices=[('RATING', 'Derecelendirme'), ('YES_NO', 'Evet / Hayır'), ('OPTION', 'Seçenek'), ('SHORT_TEXT', 'Kısa Metin')], default='RATING', max_length=20, verbose_name='Cevap tipi')),
                ('question_role', models.CharField(choices=[('NONE', 'Genel'), ('NPS', 'NPS'), ('FOOD', 'Yemek'), ('SERVICE', 'Servis'), ('SPEED', 'Hız'), ('CLEANLINESS', 'Temizlik')], default='NONE', max_length=20, verbose_name='Analitik rol')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('placeholder', models.CharField(blank=True, default='', max_length=200, verbose_name='Yer tutucu')),
                ('rating_min_value', models.PositiveSmallIntegerField(default=1, verbose_name='Min puan')),
                ('rating_max_value', models.PositiveSmallIntegerField(default=5, verbose_name='Maks puan')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='guest_feedback.survey', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Anket sorusu',
                'verbose_name_plural': 'Anket soruları',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=200, verbose_name='Seçenek')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='guest_feedback.surveyquestion', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Soru seçeneği',
                'verbose_name_plural': 'Soru seçenekleri',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('POS_DISPLAY', 'Müşteri Ekranı'), ('SMART_TABLE', 'Smart Table')], default='POS_DISPLAY', max_length=20, verbose_name='Kaynak')),
                ('session_key', models.CharField(max_length=200, verbose_name='Oturum anahtarı')),
                ('nps_score', models.SmallIntegerField(blank=True, null=True, verbose_name='NPS')),
                ('food_rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Yemek puanı')),
                ('service_rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Servis puanı')),
                ('speed_rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Hız puanı')),
                ('cleanliness_rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Temizlik puanı')),
                ('needs_attention', models.BooleanField(default=False, verbose_name='İlgi gerekiyor')),
                ('attention_status', models.CharField(choices=[('OPEN', 'Açık'), ('REVIEWED', 'İncelendi'), ('RESOLVED', 'Çözüldü')], default='OPEN', max_length=20, verbose_name='İlgi durumu')),
                ('attention_note', models.TextField(blank=True, default='', verbose_name='İlgi notu')),
                ('attention_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme zamanı')),
                ('attention_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen kullanıcı')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='branches.branch', verbose_name='Şube')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='customers.customer', verbose_name='Müşteri')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='orders.order', verbose_name='Sipariş')),
                ('pos_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='pos_display.posterminal', verbose_name='POS terminali')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='sales.sale', verbose_name='Satış')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='guest_feedback.survey', verbose_name='Anket')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='branches.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Anket yanıtı',
                'verbose_name_plural': 'Anket yanıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('selected_option_label', models.CharField(blank=True, default='', max_length=200, verbose_name='Seçenek etiketi')),
                ('rating_value', models.SmallIntegerField(blank=True, null=True, verbose_name='Puan')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Evet / Hayır')),
                ('text_value', models.TextField(blank=True, default='', verbose_name='Metin')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='guest_feedback.surveyquestion', verbose_name='Soru')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='guest_feedback.surveyquestionoption', verbose_name='Seçilen seçenek')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='guest_feedback.surveyresponse', verbose_name='Yanıt')),
            ],
            options={
                'verbose_name': 'Soru yanıtı',
                'verbose_name_plural': 'Soru yanıtları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSurveySessionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('POS_DISPLAY', 'Müşteri Ekranı'), ('SMART_TABLE', 'Smart Table')], default='POS_DISPLAY', max_length=20, verbose_name='Kaynak')),
                ('session_key', models.CharField(max_length=200, verbose_name='Oturum anahtarı')),
                ('status', models.CharField(choices=[('OPENED', 'Açıldı'), ('ANSWERED', 'Yanıtlandı'), ('CLOSED', 'Kapatıldı')], default='OPENED', max_length=20, verbose_name='Durum')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma zamanı')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_session_states', to='branches.branch', verbose_name='Şube')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_session_states', to='customers.customer', verbose_name='Müşteri')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_session_states', to='orders.order', verbose_name='Sipariş')),
                ('pos_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_session_states', to='pos_display.posterminal', verbose_name='POS terminali')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_session_states', to='sales.sale', verbose_name='Satış')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_session_states', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_states', to='guest_feedback.survey', verbose_name='Anket')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_session_states', to='branches.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Anket oturum durumu',
                'verbose_name_plural': 'Anket oturum durumları',
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='session_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='guest_feedback.tablesurveysessionstate', verbose_name='Oturum'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'is_customer_display_active'], name='gf_svy_cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'is_smart_table_active'], name='gf_svy_st_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'is_active', 'sort_order'], name='gf_q_survey_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestionoption',
            index=models.Index(fields=['question', 'is_active', 'sort_order'], name='gf_opt_question_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['response', 'question'], name='gf_ans_resp_q_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesurveysessionstate',
            index=models.Index(fields=['pos_terminal', 'status'], name='gf_session_terminal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesurveysessionstate',
            index=models.Index(fields=['survey', 'branch', 'status'], name='gf_session_survey_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesurveysessionstate',
            index=models.Index(fields=['sale', 'survey'], name='gf_session_sale_survey_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablesurveysessionstate',
            constraint=models.UniqueConstraint(fields=('session_key', 'survey', 'source'), name='gf_sess_key_svy_src_uq'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'branch', '-created_at'], name='gf_resp_survey_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['needs_attention', 'attention_status'], name='gf_resp_attention_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['sale', 'survey'], name='gf_resp_sale_survey_idx'),
        ),
    ]
