"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from config.load_env import load_project_env  # noqa: E402

load_project_env(BASE_DIR)


def _env_csv(name: str, default: str = '') -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


## hem electron based sistemler hem web sistemleri için giriş ayarları
def _local_frontend_origins(*ports: int) -> tuple[str, ...]:
    if not ports:
        ports = (3000, 5173, 5174)
    origins: list[str] = []
    # Her port için localhost ve 127.0.0.1
    for port in ports:
        origins.append(f'http://localhost:{port}')
        origins.append(f'http://127.0.0.1:{port}')
    # Port 80 (Nginx üzerinden erişim) — Electron/KDS için de gerekli
    origins.append('http://localhost')
    origins.append('http://127.0.0.1')
    return tuple(origins)


def _dev_csrf_origins_from_allowed_hosts(allowed_hosts: list[str]) -> list[str]:
    """DEBUG: ALLOWED_HOSTS içindeki ek host/IP için Next (3000) ve nginx (80) kökleri."""
    origins: list[str] = []
    for host in allowed_hosts:
        if host in ('localhost', '127.0.0.1'):
            continue
        origins.append(f'http://{host}:3000')
        origins.append(f'http://{host}')
    return origins


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_INSECURE_SECRET_KEY = (
    'django-insecure-rb(44of%8zk8p@p8jnw_xqo%tt@#2oqgnu5o41(opf04&esz%j'
)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# Stok rezervasyon mekanizması (Faz 3-3). Varsayılan aktif.
# Stok Rezervasyonu Ayarları
STOCK_RESERVATION_ENABLED = os.environ.get('STOCK_RESERVATION_ENABLED', 'True').lower() in ('true', '1', 'yes')
STOCK_RESERVATION_EXPIRY_HOURS = int(os.environ.get('STOCK_RESERVATION_EXPIRY_HOURS', '24'))
# INGREDIENT modunda rezervasyon oluşmazsa sipariş oluşturmayı reddet (varsayılan kapalı).
INGREDIENT_STOCK_STRICT_RESERVE = os.environ.get('INGREDIENT_STOCK_STRICT_RESERVE', '').lower() in (
    'true',
    '1',
    'yes',
)

# Üretim Stok Rezervasyonu.Varsayılan aktif.
PRODUCTION_STOCK_RESERVATION_ENABLED = os.environ.get(
    'PRODUCTION_STOCK_RESERVATION_ENABLED', 'True'
).lower() in ('true', '1', 'yes')

# Negatif lot temizleme (allow_negative_stock ile oluşan NEG lotlar)
NEGATIVE_LOT_CLEANUP_ENABLED = os.environ.get('NEGATIVE_LOT_CLEANUP_ENABLED', 'True').lower() in (
    'true',
    '1',
    'yes',
)

# FEFO lot bazlı tüketim maliyeti (hareket unit_price + plan maliyeti). Prod başlangıç: False.
FEFO_COSTING_ENABLED = os.environ.get('FEFO_COSTING_ENABLED', 'False').lower() in (
    'true',
    '1',
    'yes',
)
EXPIRY_WARNING_DAYS_DEFAULT = int(os.environ.get('EXPIRY_WARNING_DAYS_DEFAULT', '3'))
_raw_expiry_days = os.environ.get('EXPIRY_WARNING_DAYS_OPTIONS', '3,7')
EXPIRY_WARNING_DAYS_OPTIONS = [
    int(x.strip()) for x in _raw_expiry_days.split(',') if x.strip()
] if _raw_expiry_days.strip() else [3, 7]
del _raw_expiry_days

# SKT Phase-2 aksiyon otomasyonu (varsayılan kapalı — prod güvenli rollout).
EXPIRY_ACTION_AUTOMATION_ENABLED = os.environ.get(
    'EXPIRY_ACTION_AUTOMATION_ENABLED', 'False'
).lower() in ('true', '1', 'yes')
EXPIRY_FEFO_BOOST_VALUE = int(os.environ.get('EXPIRY_FEFO_BOOST_VALUE', '100'))
EXPIRY_FEFO_BOOST_HOURS = int(os.environ.get('EXPIRY_FEFO_BOOST_HOURS', '48'))
EXPIRY_PREP_PRIORITY_DELTA = int(os.environ.get('EXPIRY_PREP_PRIORITY_DELTA', '5'))
EXPIRY_TRANSFER_IDEMPOTENCY_HOURS = int(
    os.environ.get('EXPIRY_TRANSFER_IDEMPOTENCY_HOURS', '24')
)

# Smart Firing v2 — mutfak kuyruğu buffer’ı, KDS/POS bildirimleri (varsayılan kapalı).
ENABLE_SMART_FIRING_V2 = os.environ.get('ENABLE_SMART_FIRING_V2', '').lower() in ('true', '1', 'yes')
SMART_FIRING_QUEUE_DEPTH_THRESHOLD = int(os.environ.get('SMART_FIRING_QUEUE_DEPTH_THRESHOLD', '8'))
SMART_FIRING_BACKLOG_MINUTE_FACTOR = int(os.environ.get('SMART_FIRING_BACKLOG_MINUTE_FACTOR', '2'))
SMART_FIRING_QUEUE_BUFFER_CAP = int(os.environ.get('SMART_FIRING_QUEUE_BUFFER_CAP', '30'))
SMART_FIRING_LEARNED_MIN_SAMPLES = int(os.environ.get('SMART_FIRING_LEARNED_MIN_SAMPLES', '5'))
# POS/mobil: kehribar “mutfak yoğun” butonu ve sipariş sonrası toast eşiği (dk).
SMART_FIRING_UI_BUSY_THRESHOLD = max(
    1,
    min(120, int(os.environ.get('SMART_FIRING_UI_BUSY_THRESHOLD', '15'))),
)

# PDF Rapor: Düşük RAM'de WeasyPrint kapatılır (ramis_tune.sh otomatik ayarlar).
# True ise tüm PDF export endpoint'leri 503 döndürür.
DISABLE_PDF_EXPORT = os.environ.get('DISABLE_PDF_EXPORT', 'false').lower() in ('true', '1', 'yes')

# Dashboard cache TTL (saniye). ramis_tune.sh düşük RAM'de 300s yapar.
DASHBOARD_CACHE_TIMEOUT = int(os.environ.get('DASHBOARD_CACHE_TIMEOUT', '120'))

# KDS aktif sipariş cache TTL (saniye). Düşük RAM'de daha uzun — ramis_tune.sh ayarlar.
KDS_ACTIVE_CACHE_TTL = int(os.environ.get('KDS_ACTIVE_CACHE_TTL', '60'))

# KDS geri çağırma: servise gönderilmiş (READY/DELIVERED) kalemlerin drawer listesinde kalma süresi (dk).
KDS_RECALL_WINDOW_MINUTES = max(
    1,
    min(120, int(os.environ.get('KDS_RECALL_WINDOW_MINUTES', '15'))),
)

if not DEBUG:
    if not os.environ.get('DJANGO_SECRET_KEY'):
        raise ValueError(
            'Üretim modunda (DJANGO_DEBUG=false) DJANGO_SECRET_KEY ortam değişkeni zorunludur.'
        )
    if SECRET_KEY == _DEV_INSECURE_SECRET_KEY:
        raise ValueError('Üretimde repodaki varsayılan (insecure) SECRET_KEY kullanılamaz.')

ALLOWED_HOSTS = _env_csv('ALLOWED_HOSTS', 'localhost,127.0.0.1')

_csrf_extra = _env_csv('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
    *_local_frontend_origins(),
    *_csrf_extra,
    *(_dev_csrf_origins_from_allowed_hosts(ALLOWED_HOSTS) if DEBUG else []),
]))

if not DEBUG:
    # install.sh HTTP (Let's Encrypt yok) modunda SECURE_SSL_REDIRECT=false yazar. Tarayıcı
    # Secure=True çerezleri yalnızca HTTPS'te kabul eder; HTTP + Secure çerez = giriş sonrası 401
    # ve / yönlendirmesi. Oturum/JWT/CSRF çerezlerinin güvenli bayrağı aynı kararla bağlanmalı.
    _use_https = os.environ.get('SECURE_SSL_REDIRECT', 'true').lower() in ('true', '1', 'yes')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _use_https
    SESSION_COOKIE_SECURE = _use_https
    CSRF_COOKIE_SECURE = _use_https
    SECURE_HSTS_SECONDS = (
        int(os.environ.get('SECURE_HSTS_SECONDS', str(365 * 24 * 3600)))
        if _use_https
        else 0
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', 'true'
    ).lower() in ('true', '1', 'yes')
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', '').lower() in ('true', '1', 'yes')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

    # Content Security Policy (CSP)
    # Izin verilen kaynaklar: self (aynı domain), trusted CDN'ler
    # İzin verilen script kaynakları: self ve belirtilen güvenilir CDN'ler
    # İzin verilen style kaynakları: self ve unsafe-inline (TailwindCSS için gerekli olabilir)
    # İzin verilen resim kaynakları: self ve data: URIs
    # İzin verilen font kaynakları: self
    # İzin verilen connect kaynakları: self
    SECURE_CONTENT_SECURITY_POLICY = (
        "default-src 'self'; "
        "script-src 'self' https://trusted.cdn.com https://cdn.jsdelivr.net; "
        "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
        "img-src 'self' data: blob:; "
        "font-src 'self'; "
        "connect-src 'self' wss: ws:; "
        "object-src 'none'; "
        "base-uri 'self'; "
        "form-action 'self'; "
        "frame-ancestors 'self'; "
        "upgrade-insecure-requests; "
    )

    # Permissions Policy
    # Hangi API/özelliklerin kullanılabileceğini tanımlar
    # Örnek: geolocation (coğrafi konum), microphone (mikrofon), camera (kamera), vb. devre dışı
    SECURE_PERMISSIONS_POLICY = (
        "geolocation=(), "
        "microphone=(), "
        "camera=(), "
        "gyroscope=(), "
        "magnetometer=()"
    )


# Uygulama tanımları definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'django_celery_beat',

    # Custom Lib Core Modules
    'rbac',

    #Ramis Uygulamaları
    'core',
    'apps.users',
    'apps.branches',
    'apps.menu',
    'apps.orders',
    'apps.inventory',
    'apps.recipes',
    'apps.audit',
    'apps.shifts',
    'apps.sales',
    'apps.dashboard',
    'apps.invoices',
    'apps.reservations',
    'apps.warehouse',
    'apps.pos_display',
    'apps.prep_display',
    'apps.search',
    'apps.reporting',
    'apps.printing',
    'apps.production_planning',
    'apps.prep',
    'apps.performances',
    'apps.credit',
    'apps.customers',
    'apps.guest_feedback',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.DatabaseConnectionMiddleware',
    'apps.audit.middleware.AuditMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',            # i18n: Accept-Language → aktif dil
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UserPreferredLanguageMiddleware',
    'rbac.middlewares.RBACMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rbac.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Production: channels_redis.core.RedisChannelLayer + Redis
# export REDIS_URL=redis://localhost:6379/0
# İsteğe bağlı ayrım: REDIS_CACHE_URL (db/1), REDIS_CHANNELS_URL (db/2), REDIS_LOCK_URL
# Faz 3: Redis TCP bağlantı zaman aşımı (saniye)
_REDIS_SOCKET_CONNECT_TIMEOUT = int(os.environ.get('REDIS_SOCKET_CONNECT_TIMEOUT', '10'))
# channels_redis BRPOP ~5 sn; okuma timeout bunun altında kalırsa WS kopar (redis-py varsayılan 5)
_REDIS_CHANNELS_SOCKET_TIMEOUT = int(os.environ.get('REDIS_CHANNELS_SOCKET_TIMEOUT', '30'))
# channels_redis: grup/kanal kuyruğu kapasitesi ve mesaj TTL (yoğun KDS/WS için artırılabilir)
_CHANNEL_LAYER_CAPACITY = int(os.environ.get('CHANNEL_LAYER_CAPACITY', '8000'))
_CHANNEL_LAYER_EXPIRY = int(os.environ.get('CHANNEL_LAYER_EXPIRY', '120'))
_redis_url_env = os.environ.get('REDIS_URL', '')

from core.redis_urls import (  # noqa: E402
    derive_redis_db,
    redis_url_for_channel_layer,
    redis_url_with_connect_timeout,
)

if _redis_url_env:
    REDIS_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _redis_url_env)
    REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', derive_redis_db(_redis_url_env, 1))
    REDIS_CHANNELS_URL = os.environ.get('REDIS_CHANNELS_URL', derive_redis_db(_redis_url_env, 2))
    REDIS_LOCK_URL = os.environ.get('REDIS_LOCK_URL', REDIS_CACHE_URL)
else:
    REDIS_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', '')
    REDIS_CHANNELS_URL = os.environ.get('REDIS_CHANNELS_URL', '')
    REDIS_LOCK_URL = os.environ.get('REDIS_LOCK_URL', '')


if _redis_url_env:
    _redis_channels_resolved = redis_url_for_channel_layer(
        REDIS_CHANNELS_URL,
        connect_timeout_seconds=_REDIS_SOCKET_CONNECT_TIMEOUT,
        socket_timeout_seconds=_REDIS_CHANNELS_SOCKET_TIMEOUT,
    )
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [_redis_channels_resolved],
                "capacity": _CHANNEL_LAYER_CAPACITY,
                "expiry": _CHANNEL_LAYER_EXPIRY,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
if _redis_url_env and REDIS_CACHE_URL:
    try:
        import redis  # jango RedisCache bağımlılığı

        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': REDIS_CACHE_URL,
                'OPTIONS': {
                    'socket_connect_timeout': _REDIS_SOCKET_CONNECT_TIMEOUT,
                },
            },
        }
    except ImportError:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'ramis-erp-cache',
            },
        }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ramis-erp-cache',
        },
    }

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Faz 3: Bağlantı zaman aşımı — split ASGI stratejisi: core.postgres_connection
from core.postgres_connection import (
    resolve_postgres_application_name,
    resolve_postgres_conn_max_age,
)

_POSTGRES_CONNECT_TIMEOUT = int(os.environ.get('POSTGRES_CONNECT_TIMEOUT', '10'))
_POSTGRES_CONN_MAX_AGE = resolve_postgres_conn_max_age()

if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': _POSTGRES_CONN_MAX_AGE,
            # Kalıcı bağlantı yokken health check gereksiz
            'CONN_HEALTH_CHECKS': _POSTGRES_CONN_MAX_AGE > 0,
            'OPTIONS': {
                'connect_timeout': _POSTGRES_CONNECT_TIMEOUT,
                'application_name': resolve_postgres_application_name(),
                'keepalives': 1,
                'keepalives_idle': 30,
                'keepalives_interval': 10,
                'keepalives_count': 5,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# Desteklenen diller: TR (varsayılan), EN, AR, DE, RU

from django.utils.translation import gettext_lazy as _  # noqa: E402

LANGUAGE_CODE = 'tr'

LANGUAGES = [
    ('tr', _('Türkçe')),
    ('en', _('English')),
    ('ar', _('العربية')),
    ('de', _('Deutsch')),
    ('ru', _('Русский')),
    ('bg', _('Български')),
    ('sq', _('Shqip')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Celery Configuration
CELERY_BROKER_URL = REDIS_BROKER_URL
# PERF: Result backend broker'dan ayrı DB kullanır (DB /3).
# celery-task-meta-* anahtarları broker DB'sini kirletmez.
CELERY_RESULT_BACKEND = os.environ.get(
    'CELERY_RESULT_BACKEND',
    derive_redis_db(REDIS_BROKER_URL, 3) if _redis_url_env else REDIS_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 dakika
CELERY_TASK_IGNORE_RESULT = True
CELERY_RESULT_EXPIRES = int(os.environ.get('CELERY_RESULT_EXPIRES_SECONDS', '3600'))
CELERY_TASK_CREATE_MISSING_QUEUES = True

# PDF Export async settings
PDF_EXPORT_ASYNC_ENABLED = os.environ.get('PDF_EXPORT_ASYNC_ENABLED', 'true').lower() in ('true', '1', 'yes')
PDF_EXPORT_CACHE_TTL = int(os.environ.get('PDF_EXPORT_CACHE_TTL', '600'))  # 10 dakika
PDF_EXPORT_CACHE_MAX_BYTES = int(os.environ.get('PDF_EXPORT_CACHE_MAX_BYTES', str(20 * 1024 * 1024)))  # 20MB

# Redis bakım (Beat: core.tasks.cleanup_redis_stale_keys)
REDIS_MAINTENANCE_ENABLED = os.environ.get('REDIS_MAINTENANCE_ENABLED', 'true').lower() in ('1', 'true', 'yes')

# Ürün Kalmadı (86) geçmiş kayıt temizliği (Beat: purge-expired-86-nightly)
BEAT_PURGE_EXPIRED_86_ENABLED = os.environ.get('BEAT_PURGE_EXPIRED_86_ENABLED', 'false').lower() in ('1', 'true', 'yes')

# Eksik listesi yetim kayıt onarımı (Beat: repair-orphan-deficiency-reports-nightly)
DEFICIENCY_REPAIR_ENABLED = os.environ.get('DEFICIENCY_REPAIR_ENABLED', 'false').lower() in ('1', 'true', 'yes')
DEFICIENCY_REPAIR_MIN_AGE_HOURS = int(os.environ.get('DEFICIENCY_REPAIR_MIN_AGE_HOURS', '24'))
DEFICIENCY_REPAIR_ORDERED_ACTION = os.environ.get(
    'DEFICIENCY_REPAIR_ORDERED_ACTION', 'revert_to_approved',
).strip().lower()
DEFICIENCY_REPAIR_STALE_ENABLED = os.environ.get(
    'DEFICIENCY_REPAIR_STALE_ENABLED', 'false',
).lower() in ('1', 'true', 'yes')
DEFICIENCY_REPAIR_STALE_ACTION = os.environ.get('DEFICIENCY_REPAIR_STALE_ACTION', 'cancel').strip().lower()
REDIS_CELERY_RESULT_MAX_IDLE_SECONDS = int(os.environ.get('REDIS_CELERY_RESULT_MAX_IDLE_SECONDS', '3600'))
REDIS_ORDER_COUNTER_RETENTION_DAYS = int(os.environ.get('REDIS_ORDER_COUNTER_RETENTION_DAYS', '3'))
REDIS_RBAC_PERM_VERSIONS_TO_KEEP = int(os.environ.get('REDIS_RBAC_PERM_VERSIONS_TO_KEEP', '2'))
REDIS_SALES_SUMMARY_GENERATIONS_TO_KEEP = int(os.environ.get('REDIS_SALES_SUMMARY_GENERATIONS_TO_KEEP', '3'))

CELERY_PRINTING_QUEUE = 'printing'
CELERY_BROADCAST_QUEUE = 'broadcast'
CELERY_MAINTENANCE_QUEUE = 'maintenance'
CELERY_PDF_EXPORT_QUEUE = 'pdf_export'

CELERY_TASK_ROUTES = {
    'apps.printing.tasks.execute_receipt_print_job': {'queue': CELERY_PRINTING_QUEUE},
    'apps.printing.tasks.sync_all_printer_statuses': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.printing.tasks.maintain_print_job_queue': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.inventory.tasks.cleanup_expired_reservations': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.inventory.tasks.scan_expiring_lots_daily': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.warehouse.tasks.scan_kitchen_low_stock_deficiencies': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.warehouse.tasks.repair_orphan_deficiency_reports': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.orders.tasks.roll_up_product_station_timing_stats': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.branches.tasks.release_table_from_cleaning': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.branches.tasks.sweep_stale_cleaning_tables': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.reservations.tasks.notify_due_reservations': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.prep.tasks.cancel_overdue_prep_tasks': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.production_planning.tasks.purge_expired_product_day_availability': {'queue': CELERY_MAINTENANCE_QUEUE},
    'core.tasks.cleanup_redis_stale_keys': {'queue': CELERY_MAINTENANCE_QUEUE},
    'core.tasks.cleanup_stale_pos_connections': {'queue': CELERY_MAINTENANCE_QUEUE},
    'apps.orders.tasks.broadcast_kds_refresh_task': {'queue': CELERY_BROADCAST_QUEUE},
    'apps.orders.tasks.broadcast_kitchen_order_status_changed_task': {'queue': CELERY_BROADCAST_QUEUE},
    'apps.reporting.tasks.generate_report_pdf_async': {'queue': CELERY_PDF_EXPORT_QUEUE},
    'apps.invoices.tasks.generate_invoice_pdf': {'queue': CELERY_PDF_EXPORT_QUEUE},
}

# POS bağlantı temizliği (Beat: core.tasks.cleanup_stale_pos_connections)
# BEAT_POS_CONNECTIONS_CLEANUP_HOUR (varsayılan: 3), BEAT_POS_CONNECTIONS_CLEANUP_MINUTE (varsayılan: 45)

# Prep — hazırlık görevleri deadline yönetimi
PREP_TASK_CANCEL_OVERDUE_MINUTES = int(os.environ.get('PREP_TASK_CANCEL_OVERDUE_MINUTES', '60'))

# Celery Beat Schedule — ortam değişkenleri: backend/config/celery_beat_schedule.py
# Üretimde Beat `DatabaseScheduler` kullanır — görevler DB'de (PeriodicTask) tutulur.
# Deploy/migrate veya Beat env değişikliği sonrası: manage.py sync_celery_beat_schedule
from config.celery_beat_schedule import build_celery_beat_schedule  # noqa: E402

CELERY_BEAT_SCHEDULE = build_celery_beat_schedule(
    reservation_expiry_hours=STOCK_RESERVATION_EXPIRY_HOURS,
)

# Termal fiş baskısı: True ise PrintJob, API isteği içinde senkron işlenir (Celery worker gerekmez).
# Geliştirme (DEBUG=True): her zaman doğrudan yazdır; PRINT_THERMAL_SYNC ortam değişkeni yok sayılır.
# Üretim (DEBUG=False): PRINT_THERMAL_SYNC ile açılır; ayar yoksa False — Celery worker ile kuyruk (önceki davranış).
if DEBUG:
    PRINT_THERMAL_SYNC = True
elif 'PRINT_THERMAL_SYNC' in os.environ:
    PRINT_THERMAL_SYNC = os.environ['PRINT_THERMAL_SYNC'].lower() in ('1', 'true', 'yes')
else:
    PRINT_THERMAL_SYNC = False

# PrintJob kuyruk bakımı (Beat: maintain_print_job_queue)
PRINT_JOB_REQUEUE_PENDING_SECONDS = int(
    os.environ.get('PRINT_JOB_REQUEUE_PENDING_SECONDS', '45')
)
PRINT_JOB_STALE_PROCESSING_SECONDS = int(
    os.environ.get('PRINT_JOB_STALE_PROCESSING_SECONDS', '180')
)
PRINT_JOB_MAINTENANCE_BATCH_SIZE = int(
    os.environ.get('PRINT_JOB_MAINTENANCE_BATCH_SIZE', '100')
)
# ramis-worker.service --concurrency (install/update.sh varsayılan 4)
CELERY_PRINTING_WORKER_CONCURRENCY = int(
    os.environ.get('CELERY_PRINTING_WORKER_CONCURRENCY', '4')
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# Token X-Connect webhook URL tabanı (ör. https://api.ornek.com)
# Tanımlı değilse admin panelinde webhook URL gösterilmez; polling fallback kullanılır.
FISCAL_WEBHOOK_BASE_URL = os.environ.get('FISCAL_WEBHOOK_BASE_URL', '').strip()

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'core.exception_handler.api_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.auth.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        # KDS/WS tetikli çoklu istemci (POS, garson) + kısa aralıklı GET patlamaları
        'user': '500/minute',
    },
    'COERCE_DECIMAL_TO_STRING': False,
}


# Oturum / token süreleri (plan: uzun refresh süresini kısalt)
_JWT_REFRESH_DAYS = int(os.environ.get('JWT_REFRESH_TOKEN_DAYS', '3'))
_SESSION_AGE_SECONDS = int(os.environ.get('SESSION_COOKIE_AGE_SECONDS', str(3 * 24 * 3600)))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_JWT_REFRESH_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Django session çerezi (admin ve session tabanlı akışlar)
SESSION_COOKIE_AGE = _SESSION_AGE_SECONDS

CORS_ALLOW_ALL_ORIGINS = False
# Tarayıcıda "Network" URL (ör. http://192.168.x.x:3000) ile çalışırken origin localhost değildir;
# withCredentials + farklı host (örn. sayfa IP, API localhost) SameSite=Lax ile çerez gönderimini de kırar.
# Ek origin'ler: export CORS_EXTRA_ORIGINS=http://192.168.1.50:3000
_extra_cors = _env_csv('CORS_EXTRA_ORIGINS')
CORS_ALLOWED_ORIGINS = list(dict.fromkeys([
    *_local_frontend_origins(),
    *_extra_cors,
]))
if DEBUG:
    # Geliştirme: Next "Network" adresi (http://<LAN-IP>:3000) ve yerel isimler.
    # Production'da DEBUG=False ile kapalı kalır. RFC1918 özel IPv4 (10/8, 172.16–31, 192.168/16).
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://(localhost|127\.0\.0\.1):\d+$",
        r"^http://192\.168\.\d{1,3}\.\d{1,3}:\d+$",
        r"^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+$",
        r"^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}:\d+$",
    ]
CORS_ALLOW_CREDENTIALS = True
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "idempotency-key",
]

# RBAC Settings
RBAC_SCAN_EXCLUDE_APPS = ['rbac', 'admin']
# İzin değişikliklerinin daha hızlı yansıması (önceki 300 s; güvenlik analizi: 60–120 s önerisi)
RBAC_CACHE_TTL = int(os.environ.get('RBAC_CACHE_TTL', '120'))

# Müşteri ekranı WS abonelik imzası (TimestampSigner max_age saniye)
POS_DISPLAY_WS_TOKEN_MAX_AGE = int(os.environ.get('POS_DISPLAY_WS_TOKEN_MAX_AGE', str(24 * 3600)))
