# Generated by Django 6.0.3 on 2026-03-19 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Reçete Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Porsiyon Sayısı')),
                ('prep_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Hazırlık Süresi (dk)')),
                ('cook_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Pişirme Süresi (dk)')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Hazırlanış Talimatları')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='menu.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miktar')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notlar')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Reçete')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Reçete Malzemesi',
                'verbose_name_plural': 'Reçete Malzemeleri',
                'ordering': ['recipe', 'stock_item'],
                'unique_together': {('recipe', 'stock_item')},
            },
        ),
    ]
