# Generated by Django 6.0.3 on 2026-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_zone_is_takeaway'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='branches.branch', verbose_name='Kullanılacak Şubeler'),
        ),
    ]
