# Generated by Django 6.0.3 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_normalized_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='normalized_quantity',
            field=models.DecimalField(decimal_places=6, help_text='Maliyet için stok kalemi birimine normalize edilmiş miktar (envanter birim dönüşümü ile).', max_digits=12, verbose_name='Stok birimine göre miktar'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Miktar'),
        ),
    ]
