# Generated by Django 6.0.3 on 2026-04-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_combinedproductitem_product_unit'),
        ('recipes', '0005_recalculate_normalized_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='menu.product', verbose_name='Ürün'),
        ),
    ]
