# Generated by Django 6.0.4 on 2026-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Örn: 250.000', max_digits=10, null=True, verbose_name='Porsiyon Miktarı/Ağırlığı'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(blank=True, help_text='Örn: g, ml', max_length=20, null=True, verbose_name='Porsiyon Birimi'),
        ),
    ]
