# Generated by Django 6.0.4 on 2026-04-20 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_serving_quantity_recipe_serving_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kategori Kodu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recipes.recipecategory', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Reçete Kategorisi',
                'verbose_name_plural': 'Reçete Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory', verbose_name='Kategori'),
        ),
    ]
