# Generated by Django 6.0.4 on 2026-04-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipecategory_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time_per_serving',
            field=models.PositiveIntegerField(default=0, verbose_name='Porsiyon Başına Pişirme (dk)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_per_serving',
            field=models.PositiveIntegerField(default=0, verbose_name='Porsiyon Başına Hazırlık (dk)'),
        ),
    ]
