# Generated by Django 6.0.5 on 2026-05-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_expiryaction'),
        ('recipes', '0009_recipe_cook_time_per_serving_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_ingredients', to='recipes.recipe', verbose_name='Alt Reçete (Yarı Mamül)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.stockitem', verbose_name='Stok Kalemi'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stock_item__isnull', False), ('sub_recipe__isnull', True)), models.Q(('stock_item__isnull', True), ('sub_recipe__isnull', False)), _connector='OR'), name='recipe_ingredient_xor_stock_or_sub'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('stock_item__isnull', False)), fields=('recipe', 'stock_item'), name='unique_recipe_stock_item'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_recipe__isnull', False)), fields=('recipe', 'sub_recipe'), name='unique_recipe_sub_recipe'),
        ),
    ]
