# Generated by Django 6.0.5 on 2026-05-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_allergen_stockitem_allergens'),
        ('recipes', '0010_recipe_sub_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='inventory.allergen', verbose_name='İçerdiği Alerjen Maddeler'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_allergenic',
            field=models.BooleanField(default=False, help_text='Malzemelerden otomatik hesaplanır.', verbose_name='Alerjen İçerir'),
        ),
    ]
