# Generated by Django 6.0.3 on 2026-05-04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosScreenPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ui_context', models.CharField(choices=[('pos', 'POS / Kasa'), ('waiter', 'Garson')], max_length=16, verbose_name='Ekran')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Tercihler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_screen_preferences', to='users.user', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'POS ekran tercihi',
                'verbose_name_plural': 'POS ekran tercihleri',
            },
        ),
        migrations.AddConstraint(
            model_name='userposscreenpreferences',
            constraint=models.UniqueConstraint(fields=('user', 'ui_context'), name='users_pos_pref_user_context_uniq'),
        ),
    ]
