# Generated by Django 6.0.4 on 2026-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userposscreenpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('ar', 'العربية'), ('de', 'Deutsch'), ('ru', 'Русский')], default='tr', max_length=5, verbose_name='Tercih edilen dil'),
        ),
    ]
