# Generated by Django 6.0.5 on 2026-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_preferred_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
