# Generated by Django 6.0.6 on 2026-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('ar', 'العربية'), ('de', 'Deutsch'), ('ru', 'Русский'), ('bg', 'Български'), ('sq', 'Shqip')], default='tr', max_length=5, verbose_name='Tercih edilen dil'),
        ),
    ]
