# Generated by Django 6.0.3 on 2026-04-01 19:20

import apps.warehouse.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0010_zone_is_takeaway'),
        ('inventory', '0008_remove_stockitem_cost_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiving_number', models.CharField(default=apps.warehouse.models._generate_gr_number, max_length=50, unique=True, verbose_name='Mal Kabul No')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('INSPECTED', 'Kontrol Edildi'), ('ACCEPTED', 'Kabul Edildi'), ('PARTIALLY_ACCEPTED', 'Kısmen Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=30, verbose_name='Durum')),
                ('received_date', models.DateField(verbose_name='Teslim Alma Tarihi')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura No')),
                ('waybill_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='İrsaliye No')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Tutar')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_goods', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_goods', to=settings.AUTH_USER_MODEL, verbose_name='Teslim Alan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receivings', to='inventory.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Mal Kabul',
                'verbose_name_plural': 'Mal Kabul İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Beklenen Miktar')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Alınan Miktar')),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Reddedilen Miktar')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parti No')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('goods_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.goodsreceiving', verbose_name='Mal Kabul')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receiving_items', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Mal Kabul Kalemi',
                'verbose_name_plural': 'Mal Kabul Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(default=apps.warehouse.models._generate_po_number, max_length=50, unique=True, verbose_name='Sipariş No')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('ORDERED', 'Sipariş Verildi'), ('PARTIALLY_RECEIVED', 'Kısmen Teslim Alındı'), ('RECEIVED', 'Teslim Alındı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=30, verbose_name='Durum')),
                ('order_date', models.DateField(verbose_name='Sipariş Tarihi')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Beklenen Teslimat Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Tutar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceiving',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receivings', to='warehouse.purchaseorder', verbose_name='Satın Alma Siparişi'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sipariş Miktarı')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Teslim Alınan Miktar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.purchaseorder', verbose_name='Satın Alma Siparişi')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Depo Adı')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Depo Kodu')),
                ('warehouse_type', models.CharField(choices=[('MAIN', 'Ana Depo'), ('SUB', 'Ara Depo'), ('COLD', 'Soğuk Hava Deposu'), ('DRY', 'Kuru Depo'), ('RAW', 'Hammadde Deposu')], default='MAIN', max_length=20, verbose_name='Depo Tipi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('capacity_info', models.TextField(blank=True, null=True, verbose_name='Kapasite Bilgisi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Depo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='branches.branch', verbose_name='Şube')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Depo Sorumlusu')),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockCounting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('counting_number', models.CharField(default=apps.warehouse.models._generate_sc_number, max_length=50, unique=True, verbose_name='Sayım No')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('IN_PROGRESS', 'Sayım Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('APPROVED', 'Onaylandı')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('counting_date', models.DateField(verbose_name='Sayım Tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_countings', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_countings', to=settings.AUTH_USER_MODEL, verbose_name='Sayan')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_countings', to='warehouse.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok Sayımı',
                'verbose_name_plural': 'Stok Sayımları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='warehouse.warehouse', verbose_name='Hedef Depo'),
        ),
        migrations.AddField(
            model_name='goodsreceiving',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receivings', to='warehouse.warehouse', verbose_name='Hedef Depo'),
        ),
        migrations.CreateModel(
            name='WarehouseStockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Miktar')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Minimum Miktar')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_levels', to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='warehouse.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Depo Stok Seviyesi',
                'verbose_name_plural': 'Depo Stok Seviyeleri',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transfer_number', models.CharField(default=apps.warehouse.models._generate_tr_number, max_length=50, unique=True, verbose_name='Transfer No')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Onay Bekliyor'), ('IN_TRANSIT', 'Transfer Ediliyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('transfer_date', models.DateField(verbose_name='Transfer Tarihi')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouse.warehouse', verbose_name='Kaynak Depo')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouse.warehouse', verbose_name='Hedef Depo')),
            ],
            options={
                'verbose_name': 'Depo Transferi',
                'verbose_name_plural': 'Depo Transferleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Transfer Miktarı')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Hedefte Alınan Miktar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.stockitem', verbose_name='Stok Kalemi')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehousetransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Kalemi',
                'verbose_name_plural': 'Transfer Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sistem Miktarı')),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sayılan Miktar')),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Fark')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('counting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.stockcounting', verbose_name='Sayım')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counting_items', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Sayım Kalemi',
                'verbose_name_plural': 'Sayım Kalemleri',
                'ordering': ['id'],
                'unique_together': {('counting', 'stock_item')},
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['branch', 'is_active'], name='warehouse_w_branch__fbbd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouse_w_code_5edeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcounting',
            index=models.Index(fields=['counting_number'], name='warehouse_s_countin_f3f0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcounting',
            index=models.Index(fields=['warehouse', 'status'], name='warehouse_s_warehou_4c0da5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='warehouse_p_order_n_affefa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'supplier'], name='warehouse_p_status_d599c6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['warehouse', 'status'], name='warehouse_p_warehou_6b7c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiving',
            index=models.Index(fields=['receiving_number'], name='warehouse_g_receivi_34cac3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiving',
            index=models.Index(fields=['warehouse', 'status'], name='warehouse_g_warehou_a2e268_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestocklevel',
            index=models.Index(fields=['warehouse', 'stock_item'], name='warehouse_w_warehou_0ee41f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestocklevel',
            unique_together={('warehouse', 'stock_item')},
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['transfer_number'], name='warehouse_w_transfe_41fb19_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['source_warehouse', 'status'], name='warehouse_w_source__efe6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['target_warehouse', 'status'], name='warehouse_w_target__5ac38b_idx'),
        ),
    ]
