# Generated by Django 6.0.3 on 2026-04-03 17:35

import apps.warehouse.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_kitchenstation_warehouse'),
        ('inventory', '0008_remove_stockitem_cost_per_unit_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Ana Depo'), ('SUB', 'Ara Depo'), ('COLD', 'Soğuk Hava Deposu'), ('DRY', 'Kuru Depo'), ('RAW', 'Hammadde Deposu'), ('KITCHEN', 'Mutfak Deposu')], default='MAIN', max_length=20, verbose_name='Depo Tipi'),
        ),
        migrations.CreateModel(
            name='DeficiencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_number', models.CharField(default=apps.warehouse.models._generate_dr_number, max_length=50, unique=True, verbose_name='Rapor No')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('PARTIALLY_COMMITTED', 'Kısmen İşlendi'), ('COMMITTED', 'Tamamlandı / İşlendi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=30, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deficiency_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('kitchen_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deficiency_reports', to='branches.kitchenstation', verbose_name='Mutfak İstasyonu')),
                ('target_warehouse', models.ForeignKey(help_text='Malzemelerin transfer edileceği mutfağa bağlı küçük depo.', on_delete=django.db.models.deletion.PROTECT, related_name='deficiency_reports', to='warehouse.warehouse', verbose_name='Hedef Depo (Mutfak Deposu)')),
            ],
            options={
                'verbose_name': 'Eksik Listesi',
                'verbose_name_plural': 'Eksik Listeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeficiencyReportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='İstenen Miktar')),
                ('unit', models.CharField(max_length=20, verbose_name='Birim')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.deficiencyreport', verbose_name='Eksik Listesi')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deficiency_items', to='inventory.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Eksik Listesi Kalemi',
                'verbose_name_plural': 'Eksik Listesi Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='deficiencyreport',
            index=models.Index(fields=['report_number'], name='warehouse_d_report__797dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='deficiencyreport',
            index=models.Index(fields=['status'], name='warehouse_d_status_c23cb7_idx'),
        ),
    ]
