# Generated by Django 6.0.3 on 2026-04-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_warehouse_type_deficiencyreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deficiencyreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='deficiencyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deficiency_reports', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
    ]
