# Generated by Django 6.0.3 on 2026-04-03 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_kitchenstation_warehouse'),
        ('warehouse', '0003_deficiencyreport_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Depo', 'verbose_name_plural': 'Depolar'},
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='warehouse_w_branch__fbbd5a_idx',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='branches.branch', verbose_name='Şubeler'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses_old', to='branches.branch', verbose_name='Şube (Eski)'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouse_w_is_acti_5ddb4a_idx'),
        ),
    ]
