# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations

def migrate_branch_to_branches(apps, schema_editor):
    Warehouse = apps.get_model('warehouse', 'Warehouse')
    for warehouse in Warehouse.objects.all():
        if warehouse.branch:
            warehouse.branches.add(warehouse.branch)

def reverse_migrate_branches_to_branch(apps, schema_editor):
    Warehouse = apps.get_model('warehouse', 'Warehouse')
    for warehouse in Warehouse.objects.all():
        first_branch = warehouse.branches.first()
        if first_branch:
            warehouse.branch = first_branch
            warehouse.save()

class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_branch_to_branches, reverse_migrate_branches_to_branch),
    ]
