# Generated by Django 6.0.3 on 2026-04-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_migrate_warehouse_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='branch',
        ),
    ]
