# Generated by Django 6.0.3 on 2026-04-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_warehouse_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='deficiency_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='warehouse.deficiencyreport', verbose_name='Bağlı Eksik Listesi'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='deficiency_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse.deficiencyreport', verbose_name='Bağlı Eksik Listesi'),
        ),
        migrations.AlterField(
            model_name='deficiencyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('ORDERED', 'Sipariş Verildi'), ('PARTIALLY_COMMITTED', 'Kısmen İşlendi'), ('COMMITTED', 'Tamamlandı / İşlendi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=30, verbose_name='Durum'),
        ),
    ]
