# Generated by Django 6.0.3 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_purchaseorder_deficiency_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficiencyreportitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='İstenen Miktar'),
        ),
        migrations.AlterField(
            model_name='goodsreceivingitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Beklenen Miktar'),
        ),
        migrations.AlterField(
            model_name='goodsreceivingitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='goodsreceivingitem',
            name='rejected_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Reddedilen Miktar'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Sipariş Miktarı'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Teslim Alınan Miktar'),
        ),
        migrations.AlterField(
            model_name='stockcountingitem',
            name='counted_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Sayılan Miktar'),
        ),
        migrations.AlterField(
            model_name='stockcountingitem',
            name='difference',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Fark'),
        ),
        migrations.AlterField(
            model_name='stockcountingitem',
            name='system_quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Sistem Miktarı'),
        ),
        migrations.AlterField(
            model_name='warehousestocklevel',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=6, default=0, help_text='-1 = sınırsız (kritik stok kontrollerinde dikkate alınmaz).', max_digits=12, verbose_name='Minimum Miktar'),
        ),
        migrations.AlterField(
            model_name='warehousestocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Transfer Miktarı'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Hedefte Alınan Miktar'),
        ),
    ]
