# Generated by Django 6.0.3 on 2026-05-11 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0018_branchtarget'),
        ('inventory', '0017_stockmovement_inventory_s_warehou_6fdd83_idx'),
        ('warehouse', '0008_increase_decimal_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deficiencyreport',
            name='warehouse_d_status_c23cb7_idx',
        ),
        migrations.AddIndex(
            model_name='deficiencyreport',
            index=models.Index(fields=['status', 'created_at'], name='warehouse_d_status_d8bbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='deficiencyreport',
            index=models.Index(fields=['kitchen_station', 'status'], name='warehouse_d_kitchen_0de2af_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestocklevel',
            index=models.Index(fields=['stock_item', 'quantity'], name='warehouse_w_stock_i_2fe973_idx'),
        ),
    ]
