# Generated by Django 6.0.4 on 2026-04-23 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('target_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Birim')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('IN_PROGRESS', 'Hazırlanıyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Öncelik')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Son Tamamlanma Zamanı')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrarlayan Görev')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prep_tasks', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_tasks', to='branches.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_prep_tasks', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_tasks', to='branches.kitchenstation', verbose_name='Mutfak İstasyonu')),
            ],
            options={
                'verbose_name': 'Hazırlık Görevi',
                'verbose_name_plural': 'Hazırlık Görevleri',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
