# Generated by Django 6.0.4 on 2026-04-23 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('every_monday', models.BooleanField(default=True)),
                ('every_tuesday', models.BooleanField(default=True)),
                ('every_wednesday', models.BooleanField(default=True)),
                ('every_thursday', models.BooleanField(default=True)),
                ('every_friday', models.BooleanField(default=True)),
                ('every_saturday', models.BooleanField(default=True)),
                ('every_sunday', models.BooleanField(default=True)),
                ('activation_time', models.TimeField(help_text='Görevin her gün saat kaçta oluşturulacağı')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_templates', to='branches.branch')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.kitchenstation')),
            ],
            options={
                'verbose_name': 'Hazırlık Şablonu',
                'verbose_name_plural': 'Hazırlık Şablonları',
            },
        ),
    ]
