# Generated by Django 6.0.4 on 2026-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0002_preptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preptemplate',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Şablon Etkin'),
        ),
    ]
