# Generated by Django 6.0.4 on 2026-04-23 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
        ('menu', '0013_combinedproductitem_product_unit'),
        ('prep', '0003_preptemplate_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preptemplate',
            options={},
        ),
        migrations.CreateModel(
            name='PrepSmartRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Kural Adı')),
                ('target_item', models.CharField(max_length=255, verbose_name='Hazırlanacak Malzeme')),
                ('ratio', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_rules', to='menu.product')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_smart_rules', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Akıllı Hazırlık Kuralı',
                'verbose_name_plural': 'Akıllı Hazırlık Kuralları',
            },
        ),
    ]
