# Generated by Django 6.0.4 on 2026-04-25 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
        ('prep', '0005_preptask_source_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepBranchSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('management_hide_old_completed', models.BooleanField(default=False, help_text='Açıkken hazırlık yönetimi görev listesi operasyon modunda davranır: önceki gün oluşturulmuş tamamlanan görevler listelenmez.', verbose_name='Yönetimde eski tamamlananları gizle')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep_branch_settings', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Hazırlık şube ayarı',
                'verbose_name_plural': 'Hazırlık şube ayarları',
            },
        ),
    ]
