# Generated by Django 6.0.5 on 2026-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0006_prep_branch_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preptemplate',
            options={'verbose_name': 'Hazırlık Şablonu', 'verbose_name_plural': 'Hazırlık Şablonları'},
        ),
    ]
