# Generated by Django 6.0.6 on 2026-06-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_product_is_popular_is_chef_recommendation'),
        ('prep', '0008_preptemplate_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='preptask',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Bu hazırlık görevinin bağlı olduğu ürün. PrepTemplate üzerinden otomatik atanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_tasks', to='menu.product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='preptemplate',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Bu şablonun bağlı olduğu ürün. Yeni görev oluşturulurken PrepTask.product'a kopyalanır.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_templates', to='menu.product', verbose_name='Ürün'),
        ),
    ]
