# Generated by Django 6.0.6 on 2026-06-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0009_preptask_product_preptemplate_product'),
        ('production_planning', '0002_prodplan_softdelete_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='preptask',
            name='plan_line',
            field=models.ForeignKey(blank=True, help_text='Bu görevin bağlı olduğu üretim planı satırı. Plan onaylandığında otomatik atanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_tasks', to='production_planning.productionplanline', verbose_name='Üretim Planı Satırı'),
        ),
    ]
