# Generated by Django 6.0.6 on 2026-06-12 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0010_preptask_plan_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preptask',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Görevin planlanan başlangıç zamanı', null=True, verbose_name='Planlanan Başlangıç'),
        ),
        migrations.CreateModel(
            name='PrepTaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prep_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='prep.preptask', verbose_name='Hazırlık Görevi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Görev Ataması',
                'verbose_name_plural': 'Görev Atamaları',
                'indexes': [models.Index(fields=['prep_task', 'user'], name='prep_prepta_prep_ta_fa98cc_idx')],
                'unique_together': {('prep_task', 'user')},
            },
        ),
    ]
