# Generated by Django 6.0.6 on 2026-06-12 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0011_preptask_scheduled_start_preptaskassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preptaskassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='preptaskassignment',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Sisteme kayıtlı olmayan kişiler için manuel isim girişi', max_length=200, verbose_name='Görünen İsim'),
        ),
        migrations.AlterField(
            model_name='preptaskassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
