# Generated by Django 6.0.6 on 2026-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0012_alter_preptaskassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preptemplate',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Sisteme kayıtlı olmayan kişiler için manuel isim girişi. assigned_to ile birlikte kullanılmaz.', max_length=200, verbose_name='Görünen İsim'),
        ),
    ]
