# Generated by Django 6.0.3 on 2026-03-25 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounted_orders', to=settings.AUTH_USER_MODEL, verbose_name='İndirimi Uygulayan'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('ORDER', 'Sipariş İndirimi'), ('ITEM', 'Ürün İndirimi')], max_length=10, null=True, verbose_name='İndirim Türü'),
        ),
    ]
