# Generated by Django 6.0.3 on 2026-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_amount_order_discount_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Adı'),
        ),
    ]
