# Generated by Django 6.0.3 on 2026-03-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_discount_amount_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='orders.orderitem', verbose_name='Ana Ürün (Birleşik)'),
        ),
    ]
