# Generated by Django 6.0.3 on 2026-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_parent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('TABLE', 'Masa'), ('TAKEAWAY', 'Paket')], default='TABLE', max_length=20, verbose_name='Sipariş Türü'),
        ),
    ]
