# Generated by Django 6.0.4 on 2026-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_portion_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, help_text='Smart Firing için hazırlığa başlanması gereken zaman.', null=True, verbose_name='Planlanan Başlangıç Zamanı'),
        ),
    ]
