# Generated by Django 6.0.4 on 2026-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_scheduled_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_tracking_mode',
            field=models.CharField(choices=[('PRODUCT', 'Ürün Kısıtına Göre'), ('INGREDIENT', 'Hammaddeye Göre')], default='PRODUCT', max_length=20, verbose_name='Stok Takip Yöntemi'),
        ),
    ]
