# Generated by Django 6.0.4 on 2026-05-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_stock_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Günlük sıfırlanan, şubeye özel kısa numara (örn. #1, #2)', max_length=20, null=True, verbose_name='Sipariş No'),
        ),
    ]
