# Generated by Django 6.0.4 on 2026-05-07 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_branchordercounter'),
        ('menu', '0015_alter_product_gross_price_and_more'),
        ('orders', '0011_order_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='orders_orde_branch__e95c01_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='orders_orde_branch__eed405_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table', 'status'], name='orders_orde_table_i_5b8f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_3360fc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['station', 'status'], name='orders_orde_station_f7b47d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['parent_item'], name='orders_orde_parent__f65096_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['scheduled_start_time'], name='orders_orde_schedul_6e570a_idx'),
        ),
    ]
