# Generated by Django 6.0.4 on 2026-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_smart_firing_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İptal Gerekçesi Kodu'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='İptal Gerekçesi Metni'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İptal Gerekçesi Kodu'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='İptal Gerekçesi Metni'),
        ),
    ]
