# Generated by Django 6.0.5 on 2026-05-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0018_branchtarget'),
        ('orders', '0014_order_cancel_reason_code_order_cancel_reason_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takeaway_zone',
            field=models.ForeignKey(
                blank=True,
                help_text='Masasız paket siparişleri için POS’ta gruplanacak bölge.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='takeaway_orders',
                to='branches.zone',
                verbose_name='Paket bölgesi',
            ),
        ),
    ]
