# Generated by Django 6.0.5 on 2026-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_takeaway_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş Kalemi', 'verbose_name_plural': 'Sipariş Kalemleri'},
        ),
    ]
