# Generated by Django 6.0.5 on 2026-05-22 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0019_alter_branch_options_alter_table_options_and_more'),
        ('orders', '0016_alter_order_options_alter_orderitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Idempotency anahtarı')),
                ('scope', models.CharField(choices=[('order.create', 'Sipariş oluştur'), ('order.complete', 'Sipariş tamamla'), ('order.complete_table', 'Masa kapat')], max_length=32, verbose_name='Kapsam')),
                ('request_hash', models.CharField(max_length=64, verbose_name='İstek özeti')),
                ('response_status', models.PositiveSmallIntegerField(verbose_name='Yanıt durumu')),
                ('response_body', models.JSONField(default=dict, verbose_name='Yanıt gövdesi')),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_idempotency_records', to='branches.branch')),
            ],
            options={
                'verbose_name': 'POS idempotency kaydı',
                'verbose_name_plural': 'POS idempotency kayıtları',
                'indexes': [models.Index(fields=['scope', 'created_at'], name='orders_posi_scope_16443c_idx'), models.Index(fields=['branch', 'created_at'], name='orders_posi_branch__8c2634_idx')],
            },
        ),
    ]
