# Generated by Django — dashboard aggregate indexes on OrderItem

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_pos_idempotency_record'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status', 'parent_item'], name='orders_oi_status_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'status'], name='orders_oi_product_status_idx'),
        ),
    ]
