# Generated by Django 6.0.5 on 2026-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_dashboard_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_status_732d63_idx',
            old_name='orders_oi_status_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_product_2a57f7_idx',
            old_name='orders_oi_product_status_idx',
        ),
    ]
