# Generated by Django 6.0.5 on 2026-06-01 19:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_branch(apps, schema_editor):
    """Mevcut OrderItem satırlarının branch_id değerini bağlı Order'dan kopyala."""
    db_alias = schema_editor.connection.alias
    schema_editor.execute("""
        UPDATE orders_orderitem
        SET branch_id = o.branch_id
        FROM orders_order o
        WHERE orders_orderitem.order_id = o.id
          AND orders_orderitem.branch_id IS NULL
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0020_table_cleaning_status'),
        ('menu', '0020_recalculate_discount_caches'),
        ('orders', '0019_rename_orders_oi_status_parent_idx_orders_orde_status_732d63_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="order.branch_id'nin okuma performansı için kopyası. Order.save() ile güncellenir.", null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Şube (denormalize)'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['branch', 'station', 'status'], name='idx_oi_br_st_st'),
        ),
        migrations.RunPython(backfill_branch, migrations.RunPython.noop),
    ]
