# Generated by Django 6.0.6 on 2026-06-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockitem_is_returnable_and_more'),
        ('orders', '0021_orderitem_waiter_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_order_items', to='inventory.returndisposalflow', verbose_name='İade/İmha Akışı'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waste_recorded',
            field=models.BooleanField(default=False, help_text='Hazırlanmış ürün iptal edildiğinde fire stok hareketinin kaydedilip kaydedilmediğini gösterir. Double-spending koruması.', verbose_name='Fire Kaydedildi'),
        ),
    ]
