# Generated by Django 6.0.6 on 2026-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0021_branch_new_fields'),
        ('inventory', '0027_expiry_phase2_fields'),
        ('menu', '0025_add_performance_indexes'),
        ('orders', '0023_order_customer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status', 'parent_item'], name='idx_oi_order_st_par'),
        ),
    ]
