# Generated by Django 6.0.4 on 2026-05-08 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0017_kitchenstation_smart_firing_extra_buffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Eylem')),
                ('target_type', models.CharField(db_index=True, max_length=100, verbose_name='Hedef Tipi')),
                ('target_id', models.CharField(db_index=True, max_length=255, verbose_name='Hedef ID')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='Önceki Durum')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='Sonraki Durum')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Ek Veri')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Aktör')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['branch', 'created_at'], name='audit_audit_branch__ae9f09_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
            },
        ),
    ]
