# Generated by Django 6.0.5 on 2026-05-28 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0020_table_cleaning_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCallLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100, verbose_name='Masa adı')),
                ('zone_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Bölge')),
                ('source', models.CharField(default='smart_button', max_length=32, verbose_name='Kaynak')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('DISMISSED', 'Görüldü')], db_index=True, default='PENDING', max_length=16)),
                ('notified_count', models.PositiveIntegerField(default=0, verbose_name='Bildirilen garson')),
                ('called_at', models.DateTimeField(db_index=True, verbose_name='Çağrı zamanı')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Görüldü zamanı')),
                ('response_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yanıt süresi (sn)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_call_logs', to='branches.branch', verbose_name='Şube')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_waiter_calls', to=settings.AUTH_USER_MODEL, verbose_name='Görüldü yapan')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_call_logs', to='branches.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'Garson çağrı kaydı',
                'verbose_name_plural': 'Garson çağrı kayıtları',
                'ordering': ['-called_at'],
                'indexes': [models.Index(fields=['branch', 'called_at'], name='performance_branch__da3d81_idx'), models.Index(fields=['branch', 'status', 'called_at'], name='performance_branch__2ec8d5_idx'), models.Index(fields=['dismissed_by', 'called_at'], name='performance_dismiss_ca31d8_idx')],
            },
        ),
    ]
