# Generated by Django 6.0.3 on 2026-03-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_kitchenstation'),
        ('menu', '0003_alter_product_options_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Bu kategorideki ürünlerin hazırlanacağı mutfak istasyonu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='branches.kitchenstation', verbose_name='Mutfak İstasyonu'),
        ),
    ]
