# Generated by Django 6.0.3 on 2026-03-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_product_show_on_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_on_pos',
            field=models.BooleanField(default=True, help_text='Kapalıysa ürün POS satış ekranında listelenmez.', verbose_name="POS'ta göster"),
        ),
    ]
