# Generated by Django 6.0.3 on 2026-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_product_show_on_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0–100 arasında yüzdelik indirim oranı. 0 = indirim yok.', max_digits=5, verbose_name='İndirim Oranı (%)'),
        ),
    ]
