# Generated by Django 6.0.3 on 2026-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="İşaretlenirse ürün POS ekranında en üstte 'Öne Çıkanlar' kategorisinde gösterilir.", verbose_name='Öne Çıkar'),
        ),
    ]
