# Generated by Django 6.0.3 on 2026-03-27 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Birim Adı')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Ürün ana fiyatı ile çarpılır (örn: 1.50). Özel fiyat girildiyse dikkate alınmaz.', max_digits=5, verbose_name='Fiyat Çarpanı')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Birim için sabit fiyat. Girilirse çarpan hesabı yerine bu fiyat kullanılır.', max_digits=10, null=True, verbose_name='Özel Fiyat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='menu.product')),
            ],
            options={
                'verbose_name': 'Ürün Birimi',
                'verbose_name_plural': 'Ürün Birimleri',
                'ordering': ['order', 'name'],
            },
        ),
    ]
