# Generated by Django 6.0.3 on 2026-03-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_productunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='0–100 arasında yüzdelik indirim oranı. 0 = indirim yok.', max_digits=6, verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Ürün ana fiyatı ile çarpılır (örn: 1.50). Özel fiyat girildiyse dikkate alınmaz.', max_digits=10, verbose_name='Fiyat Çarpanı'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Birim için sabit fiyat. Girilirse çarpan hesabı yerine bu fiyat kullanılır.', max_digits=12, null=True, verbose_name='Özel Fiyat'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
