# Generated by Django 6.0.3 on 2026-03-27 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_modifier_price_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Birden fazla ürünün birleştirilmesiyle oluşan paket ürün.', verbose_name='Birleşik Ürün'),
        ),
        migrations.CreateModel(
            name='CombinedProductItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_items', to='menu.product', verbose_name='Birleşik Ürün')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_combined', to='menu.product', verbose_name='Alt Ürün')),
            ],
            options={
                'verbose_name': 'Birleşik Ürün Kalemi',
                'verbose_name_plural': 'Birleşik Ürün Kalemleri',
                'unique_together': {('parent_product', 'product')},
            },
        ),
    ]
