# Generated by Django 6.0.3 on 2026-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_zone_is_takeaway'),
        ('menu', '0011_product_is_combined_combinedproductitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='products', to='branches.branch', verbose_name='Satışa Sunulacak Şubeler'),
        ),
    ]
