# Generated by Django 6.0.4 on 2026-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_branchordercounter'),
        ('menu', '0014_product_gross_price_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vergi hariç birim fiyat; net satış ile birlikte saklanır.', max_digits=12, verbose_name='Brüt Fiyat (KDV hariç)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='menu_produc_is_acti_90fc76_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'show_on_pos'], name='menu_produc_is_acti_c4b163_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'order'], name='menu_produc_categor_4d110f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='menu_produc_name_86e474_idx'),
        ),
    ]
