# Generated by Django 6.0.4 on 2026-05-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_product_gross_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price_cached',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sık hesaplamaları önlemek için kaydedilen indirimli fiyat.', max_digits=12, verbose_name='İndirimli Fiyat (Cache)'),
        ),
    ]
