# Generated by Django 6.0.5 on 2026-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_combinedproductitem_decimal_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
