# Generated by Django 6.0.5 on 2026-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_show_on_menu',
            field=models.BooleanField(default=True, help_text='Kapalıysa ürün menüden kaldırılır ancak sistemde silinmiş sayılmaz.', verbose_name='Menüde Göster'),
        ),
    ]
