# Generated by Django 6.0.5 on 2026-05-19

from django.db import migrations
from decimal import Decimal

def recalculate_discount_caches(apps, schema_editor):
    Product = apps.get_model('menu', 'Product')
    products = []
    for product in Product.objects.all():
        # Recalculate discounted_price_cached
        if not (product.discount_rate and product.discount_rate > 0):
            product.discounted_price_cached = product.base_price
        else:
            factor = Decimal('1') - (Decimal(str(product.discount_rate)) / Decimal('100'))
            product.discounted_price_cached = (product.base_price * factor).quantize(Decimal('0.0001'))
        products.append(product)
    
    if products:
        Product.objects.bulk_update(products, ['discounted_price_cached'])

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_product_is_show_on_menu'),
    ]

    operations = [
        migrations.RunPython(recalculate_discount_caches, reverse_code=migrations.RunPython.noop),
    ]
