# Generated by Django 6.0.6 on 2026-06-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_product_is_popular_is_chef_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='modifiergroup',
            options={'ordering': ['name']},
        ),
    ]
