# Generated by Django 6.0.6 on 2026-07-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_productrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='product_unit',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa standart birim (ana fiyat) kullanılır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_usages', to='menu.productunit', verbose_name='Satış Birimi'),
        ),
    ]
