# Generated by Django 6.0.6 on 2026-07-02 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_product_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Etiket Adı')),
            ],
            options={
                'verbose_name': 'Menü Etiketi',
                'verbose_name_plural': 'Menü Etiketleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCatalogSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_untagged', models.BooleanField(default=False, help_text='True ise yalnızca etiketsiz ürün ve kategoriler gösterilir.', verbose_name='Etiketsiz filtresi')),
                ('active_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menutag', verbose_name='Aktif Etiket')),
            ],
            options={
                'verbose_name': 'Menü Katalog Ayarı',
                'verbose_name_plural': 'Menü Katalog Ayarları',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='menu.menutag', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu.menutag', verbose_name='Etiketler'),
        ),
    ]
