# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0007_pos_terminal'),
        ('shifts', '0002_shift_actual_card_shift_actual_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='opened_at_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shifts', to='pos_display.posterminal', verbose_name='Açıldığı Terminal'),
        ),
    ]
