# Generated by Django 6.0.5 on 2026-05-27 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0019_alter_branch_options_alter_table_options_and_more'),
        ('pos_display', '0008_displaysettings_terminal_scoped_slides'),
        ('shifts', '0003_shift_opened_at_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierPinAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pin', models.CharField(max_length=4, unique=True, verbose_name='PIN Kodu')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_pin_assignments', to='branches.branch', verbose_name='Şube')),
                ('pos_terminals', models.ManyToManyField(blank=True, related_name='cashier_pin_assignments', to='pos_display.posterminal', verbose_name='POS Terminalleri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_pin_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kasiyer PIN Ataması',
                'verbose_name_plural': 'Kasiyer PIN Atamaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
