# Generated by Django 6.0.6 on 2026-07-02 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0021_branch_new_fields'),
        ('pos_display', '0009_posterminal_fiscal_settings_posterminal_fiscal_type'),
        ('shifts', '0004_cashierpinassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'status'], name='shifts_shif_branch__28fb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', '-opened_at'], name='shifts_shif_branch__1fe28f_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status'], name='shifts_shif_status_8c03df_idx'),
        ),
    ]
