# Generated by Django 6.0.3 on 2026-04-19 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Yazıcı Adı')),
                ('connection_type', models.CharField(choices=[('NETWORK', 'Network (Ethernet/WiFi)'), ('USB', 'USB')], default='NETWORK', max_length=20, verbose_name='Bağlantı Tipi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('port', models.PositiveIntegerField(default=9100, verbose_name='Port')),
                ('device_path', models.CharField(blank=True, help_text='Linux için örn: /dev/usb/lp0', max_length=255, null=True, verbose_name='Cihaz Yolu')),
                ('printer_type', models.CharField(choices=[('EPSON', 'Epson'), ('STAR', 'Star'), ('BIXOLON', 'Bixolon'), ('GENERIC', 'Jenerik ESC/POS')], default='GENERIC', max_length=20, verbose_name='Yazıcı Modeli/Profili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Yazıcı',
                'verbose_name_plural': 'Yazıcılar',
                'ordering': ['branch', 'name'],
            },
        ),
    ]
