# Generated by Django 6.0.3 on 2026-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='usage_type',
            field=models.CharField(choices=[('KITCHEN', 'Mutfak'), ('POS', 'POS / Kasa')], default='POS', max_length=20, verbose_name='Kullanım Alanı'),
        ),
    ]
