# Generated by Django 6.0.4 on 2026-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_print_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='printjob',
            new_name='printing_pr_printer_775749_idx',
            old_name='printing_pr_printer_16a52d_idx',
        ),
        migrations.AddField(
            model_name='printer',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme'),
        ),
        migrations.AddField(
            model_name='printer',
            name='status_info',
            field=models.JSONField(blank=True, default=dict, help_text='Online/Offline, Kağıt durumu vb.', verbose_name='Durum Bilgisi'),
        ),
    ]
