# Generated by Django 6.0.4 on 2026-04-22 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
        ('menu', '0013_combinedproductitem_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_safety_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Tahmin hesaplamalarında kullanılır (Örn: %10 tolerans için 1.10)', max_digits=5, verbose_name='Varsayılan Güvenlik Çarpanı')),
                ('pos_block_mode', models.CharField(choices=[('OFF', 'Kapalı'), ('WARN', 'Uyarı Ver'), ('BLOCK', 'Siparişi Engelle')], default='WARN', help_text='Tükendi veya limiti dolan ürünler POS ekranında nasıl davranacak?', max_length=20, verbose_name='POS Engel Modu')),
                ('allow_negative_plan_variance', models.BooleanField(default=False, help_text='Planda belirlenenden daha fazla satılmasına göz yumulacak mı?', verbose_name='Negatif Plan Farkına İzin Ver')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_day_settings', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Üretim Günü Ayarı',
                'verbose_name_plural': 'Üretim Günü Ayarları',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_date', models.DateField(verbose_name='Plan Tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('APPROVED', 'Onaylı'), ('LOCKED', 'Kilitli')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Zamanı')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_plans', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='branches.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Üretim Planı',
                'verbose_name_plural': 'Üretim Planları',
                'ordering': ['-plan_date', 'branch'],
                'unique_together': {('branch', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductDayAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(verbose_name='Geçerlilik Tarihi')),
                ('mode', models.CharField(choices=[('AVAILABLE', 'Mevcut'), ('LIMITED', 'Sınırlı'), ('SOLD_OUT', 'Tükendi (Ürün Kalmadı)')], default='SOLD_OUT', help_text='Ürün satışta mı, limiti var mı, yoksa tükendi (kalmadı) mi?', max_length=20, verbose_name='Durum')),
                ('remaining_portions', models.DecimalField(blank=True, decimal_places=3, help_text='Durum "Sınırlı" seçilirse geçerlidir.', max_digits=10, null=True, verbose_name='Kalan Porsiyon')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Sebep')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availabilities', to='branches.branch', verbose_name='Şube')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availabilities', to='menu.product', verbose_name='Ürün')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_product_availabilities', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Ürün Kalmadı (86) Kaydı',
                'verbose_name_plural': 'Ürün Kalmadı (86) Kayıtları',
                'ordering': ['-effective_date', 'product__name'],
                'unique_together': {('branch', 'effective_date', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Hedef Miktar (Porsiyon)')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('FORECAST', 'Tahmin'), ('IMPORT', 'İçe Aktarma')], default='MANUAL', max_length=20, verbose_name='Kaynak')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production_planning.productionplan', verbose_name='Plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plan_lines', to='menu.product', verbose_name='Ürün')),
                ('station', models.ForeignKey(blank=True, help_text='Ürünün hazırlandığı istasyon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plan_lines', to='branches.kitchenstation', verbose_name='Mutfak İstasyonu')),
            ],
            options={
                'verbose_name': 'Üretim Planı Satırı',
                'verbose_name_plural': 'Üretim Planı Satırları',
                'ordering': ['plan', 'product__name'],
                'unique_together': {('plan', 'product')},
            },
        ),
    ]
