# Generated by Django 6.0.3 on 2026-04-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0011_kitchenstation_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_timeout', models.IntegerField(default=30, help_text='Saniye cinsinden bekleme süresi')),
                ('transition_speed', models.IntegerField(default=5, help_text='Slaytlar arası geçiş hızı (saniye)')),
                ('show_clock', models.BooleanField(default=True, help_text='Ekranda saat gösterilsin mi?')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_settings', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Ekran Ayarı',
                'verbose_name_plural': 'Ekran Ayarları',
            },
        ),
        migrations.CreateModel(
            name='PromotionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='pos/promotions/', verbose_name='Görsel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('duration', models.IntegerField(default=10, help_text='Bu slaytın ekranda kalma süresi (saniye)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_slides', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Tanıtım Slaytı',
                'verbose_name_plural': 'Tanıtım Slaytları',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
