# Generated by Django 6.0.3 on 2026-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysettings',
            name='welcome_subtitle',
            field=models.CharField(default='Şeffaf ve Profesyonel Hizmet', max_length=255, verbose_name='Karşılama Alt Başlığı'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='welcome_title',
            field=models.CharField(default='RAMIS ERP', max_length=200, verbose_name='Karşılama Başlığı'),
        ),
        migrations.AddField(
            model_name='promotionslide',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Görsel'), ('TEXT', 'Metin')], default='IMAGE', max_length=10, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pos/promotions/', verbose_name='Görsel'),
        ),
    ]
