# Generated by Django 6.0.3 on 2026-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0002_displaysettings_welcome_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysettings',
            name='order_success_subtitle',
            field=models.CharField(default='Mutfağa iletildi, hazırlanıyor...', max_length=255, verbose_name='Sipariş Başarı Alt Başlığı'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='order_success_title',
            field=models.CharField(default='Siparişiniz Alındı', max_length=200, verbose_name='Sipariş Başarı Başlığı'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='payment_success_subtitle',
            field=models.CharField(default='Afiyet olsun, yine bekleriz.', max_length=255, verbose_name='Ödeme Başarı Alt Başlığı'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='payment_success_title',
            field=models.CharField(default='Teşekkürler', max_length=200, verbose_name='Ödeme Başarı Başlığı'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='success_message_duration',
            field=models.IntegerField(default=5, help_text='Başarı mesajının ekranda kalma süresi (saniye)'),
        ),
    ]
