# Generated by Django 6.0.3 on 2026-04-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0004_basemodel_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
