# Generated by Django 6.0.3 on 2026-04-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0005_alter_displaysettings_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaysettings',
            options={'ordering': ['created_at'], 'verbose_name': 'Ekran Ayarı', 'verbose_name_plural': 'Ekran Ayarları'},
        ),
    ]
