# Generated by Django 6.0.3 on 2026-04-05 16:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_default_pos_terminals(apps, schema_editor):
    Branch = apps.get_model("branches", "Branch")
    PosTerminal = apps.get_model("pos_display", "PosTerminal")
    for b in Branch.objects.all():
        if not PosTerminal.objects.filter(branch_id=b.pk, code="kasa-01").exists():
            PosTerminal.objects.create(
                branch_id=b.pk,
                code="kasa-01",
                name="Varsayılan kasa",
                sort_order=0,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_branch_currency_branch_invoice_prefix_and_more'),
        ('pos_display', '0006_alter_displaysettings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='Kanal kodu (örn. kasa-1); müşteri ekranı URL/WS ile uyumlu olmalıdır.', max_length=64, validators=[django.core.validators.RegexValidator(message='Kod yalnızca harf, rakam, alt çizgi ve tire içerebilir.', regex='^[\\w-]+$')])),
                ('name', models.CharField(max_length=120, verbose_name='Görünen ad')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='branches.branch')),
            ],
            options={
                'verbose_name': 'POS terminali',
                'verbose_name_plural': 'POS terminalleri',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'code'), name='uniq_pos_terminal_branch_code')],
            },
        ),
        migrations.RunPython(seed_default_pos_terminals, migrations.RunPython.noop),
    ]
