# Generated by Django 6.0.6 on 2026-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0008_displaysettings_terminal_scoped_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='fiscal_settings',
            field=models.JSONField(blank=True, default=dict, help_text='IP, Port, Seri Port, API Key vb. parametreleri JSON olarak saklar.', verbose_name='Mali Entegrasyon Ayarları'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='fiscal_type',
            field=models.CharField(choices=[('NONE', 'Yok (Mali Entegrasyon Devre Dışı)'), ('MOCK', 'Sanal Entegrasyon (Test/Simülasyon)'), ('BEKO_GMP3', 'Beko ÖKC (GMP3 Bulut/Lokal)'), ('HUGIN_GMP3', 'Hugin ÖKC (GMP3 Lokal/Socket)'), ('EARSIV_UYUMSOFT', 'Uyumsoft e-Arşiv Fatura')], default='NONE', max_length=30, verbose_name='Mali Entegrasyon Türü'),
        ),
    ]
