# Generated by Django 6.0.6 on 2026-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0009_posterminal_fiscal_settings_posterminal_fiscal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='displaysettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='promotionslide',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
