# Generated by Django 6.0.5 on 2026-05-29 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0020_table_cleaning_status'),
        ('sales', '0011_alter_sale_original_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Soyad')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('is_global', models.BooleanField(default=False, help_text='İşaretliyse hesap herhangi bir şubede kullanılabilir.', verbose_name='Tüm Şubelerde Geçerli')),
                ('credit_policy', models.CharField(choices=[('BLOCK', 'Bakiye yetersizse engelle'), ('WARN_ALLOW', 'Uyar ama satışa izin ver'), ('OPEN_TAB', 'Açık hesap (limitsiz)')], default='BLOCK', max_length=12, verbose_name='Bakiye Politikası')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_accounts', to='branches.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Sistem Kullanıcısı')),
            ],
            options={
                'verbose_name': 'Ödenmez Hesabı',
                'verbose_name_plural': 'Ödenmez Hesapları',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Kredi Yükleme'), ('CHARGE', 'Harcama')], max_length=10, verbose_name='Hareket Türü')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tutar')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit.creditaccount', verbose_name='Hesap')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='branches.branch', verbose_name='Şube')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='sales.sale', verbose_name='Satış')),
            ],
            options={
                'verbose_name': 'Ödenmez Hareketi',
                'verbose_name_plural': 'Ödenmez Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['is_active', 'branch'], name='credit_cred_is_acti_1a3c03_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['is_active', 'is_global'], name='credit_cred_is_acti_065ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['user'], name='credit_cred_user_id_0adc9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('user',), name='uniq_active_credit_account_per_user'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['account', '-created_at'], name='credit_cred_account_6c8852_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type'], name='credit_cred_transac_56c4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['sale'], name='credit_cred_sale_id_1ccb3c_idx'),
        ),
    ]
