# Generated by Django 6.0.2 on 2026-03-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kategori Kodu')),
            ],
            options={
                'verbose_name': 'İzin Kategorisi',
                'verbose_name_plural': 'İzin Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İzin Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='İzin Kodu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.permissioncategory', verbose_name='İzin Kategorisi')),
            ],
            options={
                'verbose_name': 'Rol İzni',
                'verbose_name_plural': 'Rol İzinleri',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rol Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.rolepermission', verbose_name='İzinler')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'ordering': ['name'],
            },
        ),
    ]
