# Generated by Django 6.0.2 on 2026-03-01 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='rbac.role', verbose_name='Üst Rol'),
        ),
        migrations.CreateModel(
            name='RBACAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Oluşturma'), ('update', 'Güncelleme'), ('delete', 'Silme'), ('assign', 'Atama'), ('revoke', 'Geri Alma')], max_length=20, verbose_name='İşlem')),
                ('target_type', models.CharField(choices=[('role', 'Rol'), ('permission', 'İzin'), ('category', 'Kategori'), ('user_role', 'Kullanıcı-Rol')], max_length=20, verbose_name='Hedef Tipi')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hedef ID')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='Hedef Özeti')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Değişiklik Detayları')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'RBAC Denetim Kaydı',
                'verbose_name_plural': 'RBAC Denetim Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
