# Generated by Django 6.0.3 on 2026-03-19 08:42

import rbac.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_add_parent_role_and_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissioncategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[rbac.models.category._validate_identifier_code], verbose_name='Kategori Kodu'),
        ),
    ]
