# Generated by Django 6.0.2 on 2026-03-19 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='branches', to=settings.AUTH_USER_MODEL, verbose_name='Şube Üyeleri'),
        ),
    ]
