# Generated by Django 6.0.2 on 2026-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='min_capacity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'Yuvarlak'), ('SQUARE', 'Kare'), ('RECTANGLE', 'Dikdörtgen')], default='SQUARE', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Küçük (1-2 Kişi)'), ('MEDIUM', 'Orta (3-4 Kişi)'), ('LARGE', 'Büyük (5-8 Kişi)'), ('EXTRA_LARGE', 'Çok Büyük (8+ Kişi)')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('FREE', 'Boş'), ('OCCUPIED', 'Dolu'), ('RESERVED', 'Rezerve'), ('OUT_OF_SERVICE', 'Hizmet Dışı')], default='FREE', max_length=20),
        ),
    ]
