# Generated by Django 6.0.2 on 2026-03-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_table_reservation_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['zone__name', 'table_number']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name']},
        ),
    ]
