# Generated by Django 6.0.3 on 2026-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_table_options_alter_zone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(blank=True, default='#f8fafc', max_length=20),
        ),
    ]
