# Generated by Django 6.0.3 on 2026-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_zone_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='zone',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
