# Generated by Django 6.0.3 on 2026-03-24 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_zone_options_zone_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='İstasyon Adı')),
                ('code', models.SlugField(verbose_name='Kod')),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=20, verbose_name='Renk')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Mutfak İstasyonu',
                'verbose_name_plural': 'Mutfak İstasyonları',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'code')},
            },
        ),
    ]
