# Generated by Django 6.0.3 on 2026-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_kitchenstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_takeaway',
            field=models.BooleanField(default=False, verbose_name='Paket Bölgesi'),
        ),
    ]
