# Generated by Django 6.0.3 on 2026-04-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_zone_is_takeaway'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstation',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_stations', to='warehouse.warehouse', verbose_name='Depo'),
        ),
    ]
