# Generated by Django 6.0.3 on 2026-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_kitchenstation_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(default='TRY', max_length=3, verbose_name='Para birimi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Fatura ön eki'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vergi oranı (%)'),
        ),
    ]
