# Generated by Django 6.0.3 on 2026-04-07 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_branch_currency_branch_invoice_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterBranchAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_branch_assignments', to='branches.branch')),
                ('tables', models.ManyToManyField(blank=True, related_name='waiter_assignments_by_table', to='branches.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_branch_assignments', to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(blank=True, related_name='waiter_assignments_by_zone', to='branches.zone')),
            ],
            options={
                'verbose_name': 'Garson şube ataması',
                'verbose_name_plural': 'Garson şube atamaları',
                'unique_together': {('user', 'branch')},
            },
        ),
    ]
