# Generated by Django 6.0.3 on 2026-04-15 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_waiter_branch_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookStationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_station_assignments', to='branches.branch')),
                ('stations', models.ManyToManyField(blank=True, related_name='cook_assignments', to='branches.kitchenstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_station_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aşçı istasyon ataması',
                'verbose_name_plural': 'Aşçı istasyon atamaları',
                'unique_together': {('user', 'branch')},
            },
        ),
    ]
