# Generated by Django 6.0.4 on 2026-05-07 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_managerbranchassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOrderCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_counters', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Şube Sipariş Sayacı',
                'verbose_name_plural': 'Şube Sipariş Sayaçları',
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
