# Generated by Django 6.0.4 on 2026-05-09 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0017_kitchenstation_smart_firing_extra_buffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Ay (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('target_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Hedef Ciro')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='branches.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Şube Hedefi',
                'verbose_name_plural': 'Şube Hedefleri',
                'ordering': ['-year', '-month', 'branch'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
    ]
