# Generated by Django 6.0.5 on 2026-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0018_branchtarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Şube', 'verbose_name_plural': 'Şubeler'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['zone__name', 'table_number'], 'verbose_name': 'Masa', 'verbose_name_plural': 'Masalar'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Bölge', 'verbose_name_plural': 'Bölgeler'},
        ),
    ]
