# Generated by Django 6.0.5 on 2026-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0020_table_cleaning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/', verbose_name='Şube Logosu'),
        ),
        migrations.AddField(
            model_name='branch',
            name='mersis_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mersis No'),
        ),
        migrations.AddField(
            model_name='branch',
            name='registry_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sicil No'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_office',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web adresi'),
        ),
    ]
