# Generated by Django 6.0.6 on 2026-06-18 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('CORPORATE', 'Kurumsal')], default='INDIVIDUAL', max_length=20, verbose_name='Müşteri Tipi')),
                ('name', models.CharField(max_length=255, verbose_name='Müşteri Adı / Firma Adı')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('web_address', models.URLField(blank=True, default='', verbose_name='Web Adresi')),
                ('tax_office', models.CharField(blank=True, default='', max_length=100, verbose_name='Vergi Dairesi')),
                ('tax_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Vergi Numarası')),
                ('tc_no', models.CharField(blank=True, default='', max_length=11, verbose_name='T.C. Kimlik Numarası')),
                ('mersis_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Mersis Numarası')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='customers_c_is_acti_f9ced9_idx'), models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx')],
            },
        ),
    ]
