# Generated by Django 6.0.2 on 2026-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='original_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('CARD', 'Kredi Kartı'), ('OTHER', 'Diğer')], max_length=10),
        ),
    ]
