# Generated by Django 6.0.3 on 2026-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_discount_amount_sale_discount_applied_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='İndirim Tutarı'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
