# Generated by Django 6.0.3 on 2026-04-05 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_discount_amount_alter_sale_total_amount'),
        ('shifts', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_split_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shifts.shift'),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Nakit'), ('CARD', 'Kredi Kartı'), ('OTHER', 'Diğer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Satış Ödemesi',
                'verbose_name_plural': 'Satış Ödemeleri',
                'ordering': ['created_at'],
            },
        ),
    ]
