# Generated by Django 6.0.3 on 2026-04-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0007_pos_terminal'),
        ('sales', '0006_sale_is_split_payment_sale_shift_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos_display.posterminal', verbose_name='POS terminali'),
        ),
    ]
