# Generated by Django 6.0.4 on 2026-05-07 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0016_branchordercounter'),
        ('orders', '0012_order_orders_orde_branch__e95c01_idx_and_more'),
        ('pos_display', '0007_pos_terminal'),
        ('sales', '0007_pos_terminal'),
        ('shifts', '0003_shift_opened_at_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-paid_at'], name='sales_sale_branch__b62221_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['paid_at'], name='sales_sale_paid_at_a2beea_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_deleted', '-paid_at'], name='sales_sale_is_dele_79248b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='sales_sale_payment_7823e1_idx'),
        ),
    ]
