# Generated by Django — dashboard/report query indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_sales_sale_branch__b62221_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_deleted', 'branch', 'paid_at'], name='sales_sale_is_del_branch_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale', 'payment_method'], name='sales_salepay_sale_method_idx'),
        ),
    ]
