# Generated by Django 6.0.5 on 2026-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salepayment_sale_dashboard_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_is_dele_332ce2_idx',
            old_name='sales_sale_is_del_branch_paid_idx',
        ),
        migrations.RenameIndex(
            model_name='salepayment',
            new_name='sales_salep_sale_id_81ed84_idx',
            old_name='sales_salepay_sale_method_idx',
        ),
    ]
