# Generated by Django 6.0.5 on 2026-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_sales_sale_is_del_branch_paid_idx_sales_sale_is_dele_332ce2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='original_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('CARD', 'Kredi Kartı'), ('OTHER', 'Diğer'), ('CREDIT', 'Ödenmez')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Nakit'), ('CARD', 'Kredi Kartı'), ('OTHER', 'Diğer'), ('CREDIT', 'Ödenmez')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Nakit'), ('CARD', 'Kredi Kartı'), ('OTHER', 'Diğer'), ('CREDIT', 'Ödenmez')], max_length=10),
        ),
    ]
