# Generated by Django 6.0.6 on 2026-06-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockitem_is_returnable_and_more'),
        ('sales', '0011_alter_sale_original_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='return_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to='inventory.returndisposalflow', verbose_name='İade/İmha Akışı'),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_reason_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='İade Gerekçe Kodu'),
        ),
        migrations.AddField(
            model_name='sale',
            name='return_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='İade Gerekçe Metni'),
        ),
    ]
