# Generated by Django 6.0.6 on 2026-06-16 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0020_table_cleaning_status'),
        ('inventory', '0022_stockitem_is_returnable_and_more'),
        ('orders', '0022_orderitem_return_flow_orderitem_waste_recorded'),
        ('pos_display', '0008_displaysettings_terminal_scoped_slides'),
        ('sales', '0012_sale_return_flow_sale_return_reason_code_and_more'),
        ('shifts', '0004_cashierpinassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_deleted', 'branch', '-paid_at'], name='sales_sale_del_br_paidat_idx'),
        ),
    ]
