# Generated by Django 6.0.6 on 2026-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sale_paid_at_date_expression_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_sale_del_br_paidat_idx',
        ),
    ]
