# Generated by Django 6.0.6 on 2026-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_sale_sales_sale_del_br_paidat_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='fiscal_printed',
            field=models.BooleanField(default=False, verbose_name='Mali Fiş Basıldı mı'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='Mali Karekod Verisi'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Mali Ham Yanıt'),
        ),
        migrations.AddField(
            model_name='sale',
            name='okc_receipt_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ÖKC Mali Fiş Zamanı'),
        ),
        migrations.AddField(
            model_name='sale',
            name='okc_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ÖKC Fiş No'),
        ),
        migrations.AddField(
            model_name='sale',
            name='okc_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ÖKC Seri No'),
        ),
        migrations.AddField(
            model_name='sale',
            name='okc_z_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Z Raporu No'),
        ),
    ]
