# Generated by Django 6.0.5 on 2026-06-26 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_display', '0009_posterminal_fiscal_settings_posterminal_fiscal_type'),
        ('sales', '0016_sale_fiscal_printed_sale_fiscal_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPendingBasket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('basket_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal'), ('FAILED', 'Hata')], db_index=True, default='PENDING', max_length=16)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pos_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_pending_baskets', to='pos_display.posterminal')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_pending_baskets', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Bekleyen mali sepet',
                'verbose_name_plural': 'Bekleyen mali sepetler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sales_fisca_status_2ed944_idx'), models.Index(fields=['pos_terminal', 'status'], name='sales_fisca_pos_ter_97ce82_idx')],
            },
        ),
    ]
